
-- Update Level 1 (beginner) curriculum to match PIXO phonics curriculum
-- Phase 1: Sound Awareness (Days 1-30)
UPDATE lessons SET title = '/a/ Sound Discovery', description = 'Listen and identify the /a/ sound in apple, ant, and alligator', vocabulary = '[{"word":"apple","phonetic":"/ˈæpəl/","meaning":"A round red fruit"},{"word":"ant","phonetic":"/ænt/","meaning":"A tiny insect"},{"word":"alligator","phonetic":"/ˈælɪɡeɪtər/","meaning":"A big reptile"}]'::jsonb, sentences = '[{"text":"I see an apple","tip":"Listen for the /a/ at the start"},{"text":"The ant is small","tip":"Can you hear /a/ in ant?"},{"text":"A big alligator","tip":"Alligator starts with /a/"}]'::jsonb, read_aloud_text = 'Apple, ant, alligator. They all start with the /a/ sound! Can you say /a/?' WHERE level = 'beginner' AND day_number = 1;

UPDATE lessons SET title = '/e/ Sound Discovery', description = 'Listen and identify the /e/ sound in egg, elephant, and elbow', vocabulary = '[{"word":"egg","phonetic":"/ɛɡ/","meaning":"Comes from a hen"},{"word":"elephant","phonetic":"/ˈɛlɪfənt/","meaning":"A huge animal with a trunk"},{"word":"elbow","phonetic":"/ˈɛlboʊ/","meaning":"The bend in your arm"}]'::jsonb, sentences = '[{"text":"I eat an egg","tip":"Listen for /e/ in egg"},{"text":"The elephant is big","tip":"Elephant starts with /e/"},{"text":"Touch your elbow","tip":"Elbow starts with /e/"}]'::jsonb, read_aloud_text = 'Egg, elephant, elbow. They all start with the /e/ sound! Say /e/ with me!' WHERE level = 'beginner' AND day_number = 2;

UPDATE lessons SET title = '/i/ Sound Discovery', description = 'Listen and identify the /i/ sound in igloo, insect, and iguana', vocabulary = '[{"word":"igloo","phonetic":"/ˈɪɡluː/","meaning":"An ice house"},{"word":"insect","phonetic":"/ˈɪnsɛkt/","meaning":"A tiny bug"},{"word":"iguana","phonetic":"/ɪˈɡwɑːnə/","meaning":"A green lizard"}]'::jsonb, sentences = '[{"text":"An igloo is cold","tip":"Listen for /i/ in igloo"},{"text":"The insect is tiny","tip":"Insect starts with /i/"},{"text":"I see an iguana","tip":"Iguana starts with /i/"}]'::jsonb, read_aloud_text = 'Igloo, insect, iguana. They all start with the /i/ sound! Can you say /i/?' WHERE level = 'beginner' AND day_number = 3;

UPDATE lessons SET title = '/o/ Sound Discovery', description = 'Listen and identify the /o/ sound in octopus, orange, and otter', vocabulary = '[{"word":"octopus","phonetic":"/ˈɒktəpəs/","meaning":"Sea animal with 8 arms"},{"word":"orange","phonetic":"/ˈɒrɪndʒ/","meaning":"A round citrus fruit"},{"word":"otter","phonetic":"/ˈɒtər/","meaning":"A playful water animal"}]'::jsonb, sentences = '[{"text":"An octopus swims","tip":"Listen for /o/ in octopus"},{"text":"I like oranges","tip":"Orange starts with /o/"},{"text":"The otter plays","tip":"Otter starts with /o/"}]'::jsonb, read_aloud_text = 'Octopus, orange, otter. They all start with the /o/ sound! Say /o/ with me!' WHERE level = 'beginner' AND day_number = 4;

UPDATE lessons SET title = '/u/ Sound Discovery', description = 'Listen and identify the /u/ sound in umbrella, up, and under', vocabulary = '[{"word":"umbrella","phonetic":"/ʌmˈbrɛlə/","meaning":"Keeps rain away"},{"word":"up","phonetic":"/ʌp/","meaning":"Going higher"},{"word":"under","phonetic":"/ˈʌndər/","meaning":"Below something"}]'::jsonb, sentences = '[{"text":"Open the umbrella","tip":"Listen for /u/ in umbrella"},{"text":"Look up high","tip":"Up starts with /u/"},{"text":"Hide under the table","tip":"Under starts with /u/"}]'::jsonb, read_aloud_text = 'Umbrella, up, under. They all start with the /u/ sound! Can you say /u/?' WHERE level = 'beginner' AND day_number = 5;

UPDATE lessons SET title = 'Vowel Listening Game', description = 'Listen carefully and match each sound to the right vowel: a, e, i, o, u', vocabulary = '[{"word":"apple","phonetic":"/æ/","meaning":"Which vowel sound?"},{"word":"elephant","phonetic":"/ɛ/","meaning":"Which vowel sound?"},{"word":"igloo","phonetic":"/ɪ/","meaning":"Which vowel sound?"},{"word":"octopus","phonetic":"/ɒ/","meaning":"Which vowel sound?"},{"word":"umbrella","phonetic":"/ʌ/","meaning":"Which vowel sound?"}]'::jsonb, sentences = '[{"text":"Match the sound to the picture","tip":"Listen carefully to the first sound"},{"text":"All five vowels together","tip":"a, e, i, o, u"}]'::jsonb, read_aloud_text = '/a/ /e/ /i/ /o/ /u/ — these are the five vowel sounds! Can you say them all?' WHERE level = 'beginner' AND day_number = 6;

UPDATE lessons SET title = 'Vowel Checkpoint', description = 'Show what you know! Identify all five vowel sounds correctly', vocabulary = '[{"word":"ant","phonetic":"/æ/","meaning":"Starts with /a/"},{"word":"egg","phonetic":"/ɛ/","meaning":"Starts with /e/"},{"word":"insect","phonetic":"/ɪ/","meaning":"Starts with /i/"},{"word":"orange","phonetic":"/ɒ/","meaning":"Starts with /o/"},{"word":"up","phonetic":"/ʌ/","meaning":"Starts with /u/"}]'::jsonb, sentences = '[{"text":"Say each vowel sound","tip":"Practice all five"},{"text":"Which sound does this word start with?","tip":"Listen and choose"}]'::jsonb, read_aloud_text = 'Great job learning the vowel sounds! Let us check how well you remember them!' WHERE level = 'beginner' AND day_number = 7;

-- Days 8-14: Adaptive Reinforcement
UPDATE lessons SET title = 'Vowel Sound /a/ Practice', description = 'More practice with the /a/ sound using new words and pictures', vocabulary = '[{"word":"avocado","phonetic":"/ˈævəkɑːdoʊ/","meaning":"A green fruit"},{"word":"axe","phonetic":"/æks/","meaning":"A tool for chopping"},{"word":"astronaut","phonetic":"/ˈæstrənɔːt/","meaning":"Travels to space"}]'::jsonb, sentences = '[{"text":"I like avocado","tip":"Listen for /a/"},{"text":"The astronaut flies","tip":"Astronaut starts with /a/"}]'::jsonb, read_aloud_text = 'More /a/ sound words! Avocado, axe, astronaut. Say them with me!' WHERE level = 'beginner' AND day_number = 8;

UPDATE lessons SET title = 'Vowel Sound /e/ Practice', description = 'More practice with the /e/ sound using new words', vocabulary = '[{"word":"envelope","phonetic":"/ˈɛnvəloʊp/","meaning":"Holds a letter"},{"word":"engine","phonetic":"/ˈɛndʒɪn/","meaning":"Makes cars go"},{"word":"exit","phonetic":"/ˈɛɡzɪt/","meaning":"The way out"}]'::jsonb, sentences = '[{"text":"Put it in the envelope","tip":"Listen for /e/"},{"text":"Find the exit","tip":"Exit starts with /e/"}]'::jsonb, read_aloud_text = 'More /e/ sound words! Envelope, engine, exit. Can you hear the /e/?' WHERE level = 'beginner' AND day_number = 9;

UPDATE lessons SET title = 'Vowel Sound /i/ Practice', description = 'More practice with the /i/ sound using new words', vocabulary = '[{"word":"inch","phonetic":"/ɪntʃ/","meaning":"A small measurement"},{"word":"itch","phonetic":"/ɪtʃ/","meaning":"When skin feels scratchy"},{"word":"infant","phonetic":"/ˈɪnfənt/","meaning":"A baby"}]'::jsonb, sentences = '[{"text":"Just one inch","tip":"Listen for /i/"},{"text":"The infant sleeps","tip":"Infant starts with /i/"}]'::jsonb, read_aloud_text = 'More /i/ sound words! Inch, itch, infant. Say them with me!' WHERE level = 'beginner' AND day_number = 10;

UPDATE lessons SET title = 'Vowel Sound /o/ Practice', description = 'More practice with the /o/ sound using new words', vocabulary = '[{"word":"olive","phonetic":"/ˈɒlɪv/","meaning":"A small green fruit"},{"word":"ostrich","phonetic":"/ˈɒstrɪtʃ/","meaning":"A big bird"},{"word":"ox","phonetic":"/ɒks/","meaning":"A strong animal"}]'::jsonb, sentences = '[{"text":"The ostrich runs fast","tip":"Listen for /o/"},{"text":"The ox is strong","tip":"Ox starts with /o/"}]'::jsonb, read_aloud_text = 'More /o/ sound words! Olive, ostrich, ox. Can you hear the /o/?' WHERE level = 'beginner' AND day_number = 11;

UPDATE lessons SET title = 'Vowel Sound /u/ Practice', description = 'More practice with the /u/ sound using new words', vocabulary = '[{"word":"ugly","phonetic":"/ˈʌɡli/","meaning":"Not pretty"},{"word":"uncle","phonetic":"/ˈʌŋkəl/","meaning":"Your parent''s brother"},{"word":"umpire","phonetic":"/ˈʌmpaɪər/","meaning":"Makes decisions in a game"}]'::jsonb, sentences = '[{"text":"My uncle is kind","tip":"Listen for /u/"},{"text":"The umpire decides","tip":"Umpire starts with /u/"}]'::jsonb, read_aloud_text = 'More /u/ sound words! Ugly, uncle, umpire. Say them with me!' WHERE level = 'beginner' AND day_number = 12;

UPDATE lessons SET title = 'Mixed Vowel Challenge', description = 'Mix and match all five vowel sounds in a fun challenge', vocabulary = '[{"word":"apple","phonetic":"/æ/","meaning":"/a/ sound"},{"word":"egg","phonetic":"/ɛ/","meaning":"/e/ sound"},{"word":"igloo","phonetic":"/ɪ/","meaning":"/i/ sound"},{"word":"octopus","phonetic":"/ɒ/","meaning":"/o/ sound"},{"word":"umbrella","phonetic":"/ʌ/","meaning":"/u/ sound"}]'::jsonb, sentences = '[{"text":"Which vowel do you hear?","tip":"Listen to the first sound"},{"text":"Say each vowel sound","tip":"a, e, i, o, u"}]'::jsonb, read_aloud_text = 'Mix them all up! Apple, egg, igloo, octopus, umbrella. Which vowel sound do you hear?' WHERE level = 'beginner' AND day_number = 13;

UPDATE lessons SET title = 'Vowel Sound Review', description = 'Review and strengthen all five vowel sounds before the mastery gate', vocabulary = '[{"word":"alligator","phonetic":"/æ/","meaning":"/a/ sound"},{"word":"elephant","phonetic":"/ɛ/","meaning":"/e/ sound"},{"word":"iguana","phonetic":"/ɪ/","meaning":"/i/ sound"},{"word":"otter","phonetic":"/ɒ/","meaning":"/o/ sound"},{"word":"under","phonetic":"/ʌ/","meaning":"/u/ sound"}]'::jsonb, sentences = '[{"text":"I know all five vowels","tip":"Practice makes perfect"},{"text":"a, e, i, o, u","tip":"The five vowel sounds"}]'::jsonb, read_aloud_text = 'You have learned all five vowel sounds! Let us review them one more time before the big challenge!' WHERE level = 'beginner' AND day_number = 14;

UPDATE lessons SET title = 'Vowel Mastery Gate', description = 'Prove your mastery of all five vowel sounds to unlock the next phase!', vocabulary = '[{"word":"apple","phonetic":"/æ/","meaning":"Say the vowel sound"},{"word":"elephant","phonetic":"/ɛ/","meaning":"Say the vowel sound"},{"word":"igloo","phonetic":"/ɪ/","meaning":"Say the vowel sound"},{"word":"octopus","phonetic":"/ɒ/","meaning":"Say the vowel sound"},{"word":"umbrella","phonetic":"/ʌ/","meaning":"Say the vowel sound"}]'::jsonb, sentences = '[{"text":"I can hear all vowels","tip":"You are a vowel champion!"},{"text":"Vowels are my superpower","tip":"Celebrate your learning!"}]'::jsonb, read_aloud_text = 'Congratulations! You have mastered all five vowel sounds! You are a vowel superstar!' WHERE level = 'beginner' AND day_number = 15;

-- Phase 1 continued: Consonant Sounds (Days 16-30)
UPDATE lessons SET title = '/b/ Sound Discovery', description = 'Listen and identify the /b/ sound in ball, bear, and banana', vocabulary = '[{"word":"ball","phonetic":"/bɔːl/","meaning":"Round and bouncy"},{"word":"bear","phonetic":"/bɛər/","meaning":"A big furry animal"},{"word":"banana","phonetic":"/bəˈnɑːnə/","meaning":"A yellow fruit"}]'::jsonb, sentences = '[{"text":"Bounce the ball","tip":"Listen for /b/"},{"text":"The bear is big","tip":"Bear starts with /b/"},{"text":"I eat a banana","tip":"Banana starts with /b/"}]'::jsonb, read_aloud_text = 'Ball, bear, banana. They all start with the /b/ sound!' WHERE level = 'beginner' AND day_number = 16;

UPDATE lessons SET title = '/k/ Sound Discovery', description = 'Listen and identify the /k/ sound in cat, cup, and cake', vocabulary = '[{"word":"cat","phonetic":"/kæt/","meaning":"A furry pet"},{"word":"cup","phonetic":"/kʌp/","meaning":"You drink from it"},{"word":"cake","phonetic":"/keɪk/","meaning":"A sweet treat"}]'::jsonb, sentences = '[{"text":"The cat purrs","tip":"Listen for /k/"},{"text":"Drink from the cup","tip":"Cup starts with /k/"},{"text":"I love cake","tip":"Cake starts with /k/"}]'::jsonb, read_aloud_text = 'Cat, cup, cake. They all start with the /k/ sound!' WHERE level = 'beginner' AND day_number = 17;

UPDATE lessons SET title = '/d/ Sound Discovery', description = 'Listen and identify the /d/ sound in dog, duck, and drum', vocabulary = '[{"word":"dog","phonetic":"/dɒɡ/","meaning":"A loyal pet"},{"word":"duck","phonetic":"/dʌk/","meaning":"A bird that swims"},{"word":"drum","phonetic":"/drʌm/","meaning":"A musical instrument"}]'::jsonb, sentences = '[{"text":"The dog barks","tip":"Listen for /d/"},{"text":"The duck quacks","tip":"Duck starts with /d/"},{"text":"Beat the drum","tip":"Drum starts with /d/"}]'::jsonb, read_aloud_text = 'Dog, duck, drum. They all start with the /d/ sound!' WHERE level = 'beginner' AND day_number = 18;

UPDATE lessons SET title = '/f/ Sound Discovery', description = 'Listen and identify the /f/ sound in fish, frog, and fan', vocabulary = '[{"word":"fish","phonetic":"/fɪʃ/","meaning":"Swims in water"},{"word":"frog","phonetic":"/frɒɡ/","meaning":"A jumping animal"},{"word":"fan","phonetic":"/fæn/","meaning":"Keeps you cool"}]'::jsonb, sentences = '[{"text":"The fish swims","tip":"Listen for /f/"},{"text":"The frog jumps","tip":"Frog starts with /f/"},{"text":"Turn on the fan","tip":"Fan starts with /f/"}]'::jsonb, read_aloud_text = 'Fish, frog, fan. They all start with the /f/ sound!' WHERE level = 'beginner' AND day_number = 19;

UPDATE lessons SET title = '/g/ Sound Discovery', description = 'Listen and identify the /g/ sound in goat, grapes, and gift', vocabulary = '[{"word":"goat","phonetic":"/ɡoʊt/","meaning":"A farm animal"},{"word":"grapes","phonetic":"/ɡreɪps/","meaning":"Small round fruits"},{"word":"gift","phonetic":"/ɡɪft/","meaning":"A present"}]'::jsonb, sentences = '[{"text":"The goat eats grass","tip":"Listen for /g/"},{"text":"I like grapes","tip":"Grapes starts with /g/"},{"text":"Open the gift","tip":"Gift starts with /g/"}]'::jsonb, read_aloud_text = 'Goat, grapes, gift. They all start with the /g/ sound!' WHERE level = 'beginner' AND day_number = 20;

UPDATE lessons SET title = '/h/ Sound Discovery', description = 'Listen and identify the /h/ sound in hat, house, and horse', vocabulary = '[{"word":"hat","phonetic":"/hæt/","meaning":"Worn on your head"},{"word":"house","phonetic":"/haʊs/","meaning":"Where you live"},{"word":"horse","phonetic":"/hɔːrs/","meaning":"A riding animal"}]'::jsonb, sentences = '[{"text":"Wear your hat","tip":"Listen for /h/"},{"text":"Go to the house","tip":"House starts with /h/"},{"text":"The horse runs","tip":"Horse starts with /h/"}]'::jsonb, read_aloud_text = 'Hat, house, horse. They all start with the /h/ sound!' WHERE level = 'beginner' AND day_number = 21;

UPDATE lessons SET title = '/j/ Sound Discovery', description = 'Listen and identify the /j/ sound in juice, jump, and jar', vocabulary = '[{"word":"juice","phonetic":"/dʒuːs/","meaning":"A fruity drink"},{"word":"jump","phonetic":"/dʒʌmp/","meaning":"Leap into the air"},{"word":"jar","phonetic":"/dʒɑːr/","meaning":"A glass container"}]'::jsonb, sentences = '[{"text":"Drink the juice","tip":"Listen for /j/"},{"text":"Jump up high","tip":"Jump starts with /j/"},{"text":"Open the jar","tip":"Jar starts with /j/"}]'::jsonb, read_aloud_text = 'Juice, jump, jar. They all start with the /j/ sound!' WHERE level = 'beginner' AND day_number = 22;

UPDATE lessons SET title = '/l/ Sound Discovery', description = 'Listen and identify the /l/ sound in lion, lamp, and leaf', vocabulary = '[{"word":"lion","phonetic":"/ˈlaɪən/","meaning":"King of the jungle"},{"word":"lamp","phonetic":"/læmp/","meaning":"Gives you light"},{"word":"leaf","phonetic":"/liːf/","meaning":"Grows on trees"}]'::jsonb, sentences = '[{"text":"The lion roars","tip":"Listen for /l/"},{"text":"Turn on the lamp","tip":"Lamp starts with /l/"},{"text":"A green leaf","tip":"Leaf starts with /l/"}]'::jsonb, read_aloud_text = 'Lion, lamp, leaf. They all start with the /l/ sound!' WHERE level = 'beginner' AND day_number = 23;

UPDATE lessons SET title = '/m/ Sound Discovery', description = 'Listen and identify the /m/ sound in moon, monkey, and mango', vocabulary = '[{"word":"moon","phonetic":"/muːn/","meaning":"Shines at night"},{"word":"monkey","phonetic":"/ˈmʌŋki/","meaning":"Climbs trees"},{"word":"mango","phonetic":"/ˈmæŋɡoʊ/","meaning":"A sweet tropical fruit"}]'::jsonb, sentences = '[{"text":"Look at the moon","tip":"Listen for /m/"},{"text":"The monkey plays","tip":"Monkey starts with /m/"},{"text":"I love mango","tip":"Mango starts with /m/"}]'::jsonb, read_aloud_text = 'Moon, monkey, mango. They all start with the /m/ sound!' WHERE level = 'beginner' AND day_number = 24;

UPDATE lessons SET title = '/n/ Sound Discovery', description = 'Listen and identify the /n/ sound in nose, nest, and nut', vocabulary = '[{"word":"nose","phonetic":"/noʊz/","meaning":"On your face for smelling"},{"word":"nest","phonetic":"/nɛst/","meaning":"Where birds live"},{"word":"nut","phonetic":"/nʌt/","meaning":"A crunchy snack"}]'::jsonb, sentences = '[{"text":"Touch your nose","tip":"Listen for /n/"},{"text":"Birds build a nest","tip":"Nest starts with /n/"},{"text":"Crack the nut","tip":"Nut starts with /n/"}]'::jsonb, read_aloud_text = 'Nose, nest, nut. They all start with the /n/ sound!' WHERE level = 'beginner' AND day_number = 25;

UPDATE lessons SET title = '/p/ Sound Discovery', description = 'Listen and identify the /p/ sound in pen, pig, and pizza', vocabulary = '[{"word":"pen","phonetic":"/pɛn/","meaning":"You write with it"},{"word":"pig","phonetic":"/pɪɡ/","meaning":"A farm animal"},{"word":"pizza","phonetic":"/ˈpiːtsə/","meaning":"A yummy round food"}]'::jsonb, sentences = '[{"text":"Write with a pen","tip":"Listen for /p/"},{"text":"The pig oinks","tip":"Pig starts with /p/"},{"text":"I want pizza","tip":"Pizza starts with /p/"}]'::jsonb, read_aloud_text = 'Pen, pig, pizza. They all start with the /p/ sound!' WHERE level = 'beginner' AND day_number = 26;

UPDATE lessons SET title = '/r/ Sound Discovery', description = 'Listen and identify the /r/ sound in rain, robot, and rabbit', vocabulary = '[{"word":"rain","phonetic":"/reɪn/","meaning":"Water from the sky"},{"word":"robot","phonetic":"/ˈroʊbɒt/","meaning":"A machine that moves"},{"word":"rabbit","phonetic":"/ˈræbɪt/","meaning":"A hopping animal"}]'::jsonb, sentences = '[{"text":"It is raining","tip":"Listen for /r/"},{"text":"The robot walks","tip":"Robot starts with /r/"},{"text":"The rabbit hops","tip":"Rabbit starts with /r/"}]'::jsonb, read_aloud_text = 'Rain, robot, rabbit. They all start with the /r/ sound!' WHERE level = 'beginner' AND day_number = 27;

UPDATE lessons SET title = '/s/ Sound Discovery', description = 'Listen and identify the /s/ sound in sun, star, and snake', vocabulary = '[{"word":"sun","phonetic":"/sʌn/","meaning":"Bright in the sky"},{"word":"star","phonetic":"/stɑːr/","meaning":"Twinkles at night"},{"word":"snake","phonetic":"/sneɪk/","meaning":"Slithers on the ground"}]'::jsonb, sentences = '[{"text":"The sun is hot","tip":"Listen for /s/"},{"text":"I see a star","tip":"Star starts with /s/"},{"text":"The snake hisses","tip":"Snake starts with /s/"}]'::jsonb, read_aloud_text = 'Sun, star, snake. They all start with the /s/ sound!' WHERE level = 'beginner' AND day_number = 28;

UPDATE lessons SET title = 'Consonant Sound Review', description = 'Review consonant sounds b, k, d, f, g, h, j, l, m, n, p, r, s', vocabulary = '[{"word":"ball","phonetic":"/b/","meaning":"/b/ sound"},{"word":"cat","phonetic":"/k/","meaning":"/k/ sound"},{"word":"dog","phonetic":"/d/","meaning":"/d/ sound"},{"word":"fish","phonetic":"/f/","meaning":"/f/ sound"},{"word":"lion","phonetic":"/l/","meaning":"/l/ sound"}]'::jsonb, sentences = '[{"text":"Say each consonant sound","tip":"Listen carefully"},{"text":"Match the sound to the word","tip":"You know these!"}]'::jsonb, read_aloud_text = 'Amazing! You have learned so many consonant sounds! Let us review them all!' WHERE level = 'beginner' AND day_number = 29;

UPDATE lessons SET title = 'Phase 1 Mastery Gate', description = 'Complete the Sound Awareness mastery challenge to unlock Phase 2!', vocabulary = '[{"word":"apple","phonetic":"/æ/","meaning":"Vowel /a/"},{"word":"ball","phonetic":"/b/","meaning":"Consonant /b/"},{"word":"cat","phonetic":"/k/","meaning":"Consonant /k/"},{"word":"dog","phonetic":"/d/","meaning":"Consonant /d/"},{"word":"elephant","phonetic":"/ɛ/","meaning":"Vowel /e/"}]'::jsonb, sentences = '[{"text":"I know all my sounds","tip":"You are a sound champion!"},{"text":"Ready for the next adventure","tip":"Phase 2 awaits!"}]'::jsonb, read_aloud_text = 'You have completed Phase 1: Sound Awareness! You are a phonics superstar! Get ready for Phase 2!' WHERE level = 'beginner' AND day_number = 30;
