-- Re-insert Level 2 (intermediate) curriculum - 180 days
INSERT INTO public.lessons (day_number, level, title, description, vocabulary, sentences, read_aloud_text, is_active) VALUES
(1, 'intermediate', 'Word Reading: Pronouns 1', 'Recognize and read common pronoun words instantly', '[{"word":"I","phonetic":"/aɪ/","meaning":"Refers to oneself"},{"word":"you","phonetic":"/juː/","meaning":"Refers to the person being spoken to"},{"word":"we","phonetic":"/wiː/","meaning":"Refers to a group including the speaker"}]', '[{"text":"I"},{"text":"you"},{"text":"we"}]', 'I, you, we. Say each word clearly.', true),
(2, 'intermediate', 'Word Reading: Pronouns 2', 'Read and pronounce personal pronouns', '[{"word":"he","phonetic":"/hiː/","meaning":"Refers to a male person"},{"word":"she","phonetic":"/ʃiː/","meaning":"Refers to a female person"},{"word":"it","phonetic":"/ɪt/","meaning":"Refers to a thing or animal"}]', '[{"text":"he"},{"text":"she"},{"text":"it"}]', 'he, she, it. Say each word clearly.', true),
(3, 'intermediate', 'Word Reading: Action Words 1', 'Read common action verbs', '[{"word":"run","phonetic":"/rʌn/","meaning":"To move quickly on foot"},{"word":"jump","phonetic":"/dʒʌmp/","meaning":"To push off the ground with your legs"},{"word":"walk","phonetic":"/wɔːk/","meaning":"To move on foot at a normal speed"}]', '[{"text":"run"},{"text":"jump"},{"text":"walk"}]', 'run, jump, walk. Say each word clearly.', true),
(4, 'intermediate', 'Word Reading: Action Words 2', 'Read daily activity verbs', '[{"word":"eat","phonetic":"/iːt/","meaning":"To put food in your mouth"},{"word":"drink","phonetic":"/drɪŋk/","meaning":"To take liquid into your mouth"},{"word":"sleep","phonetic":"/sliːp/","meaning":"To rest with eyes closed"}]', '[{"text":"eat"},{"text":"drink"},{"text":"sleep"}]', 'eat, drink, sleep. Say each word clearly.', true),
(5, 'intermediate', 'Word Reading: Action Words 3', 'Read learning activity verbs', '[{"word":"play","phonetic":"/pleɪ/","meaning":"To have fun"},{"word":"read","phonetic":"/riːd/","meaning":"To look at and understand written words"},{"word":"write","phonetic":"/raɪt/","meaning":"To make letters or words on paper"}]', '[{"text":"play"},{"text":"read"},{"text":"write"}]', 'play, read, write. Say each word clearly.', true),
(6, 'intermediate', 'Word Reading: Animals', 'Read common animal names', '[{"word":"cat","phonetic":"/kæt/","meaning":"A small furry pet animal"},{"word":"dog","phonetic":"/dɒɡ/","meaning":"A common pet animal"},{"word":"bird","phonetic":"/bɜːrd/","meaning":"An animal with wings and feathers"}]', '[{"text":"cat"},{"text":"dog"},{"text":"bird"}]', 'cat, dog, bird. Say each word clearly.', true),
(7, 'intermediate', 'Word Reading: Toys', 'Read toy-related words', '[{"word":"ball","phonetic":"/bɔːl/","meaning":"A round object used in games"},{"word":"toy","phonetic":"/tɔɪ/","meaning":"Something to play with"},{"word":"car","phonetic":"/kɑːr/","meaning":"A vehicle with four wheels"}]', '[{"text":"ball"},{"text":"toy"},{"text":"car"}]', 'ball, toy, car. Say each word clearly.', true),
(8, 'intermediate', 'Word Reading: School Items', 'Read school supply words', '[{"word":"book","phonetic":"/bʊk/","meaning":"Pages with words to read"},{"word":"pen","phonetic":"/pen/","meaning":"A tool for writing"},{"word":"bag","phonetic":"/bæɡ/","meaning":"Something to carry things in"}]', '[{"text":"book"},{"text":"pen"},{"text":"bag"}]', 'book, pen, bag. Say each word clearly.', true),
(9, 'intermediate', 'Word Reading: Adjectives 1', 'Read descriptive words', '[{"word":"big","phonetic":"/bɪɡ/","meaning":"Large in size"},{"word":"small","phonetic":"/smɔːl/","meaning":"Little in size"},{"word":"red","phonetic":"/red/","meaning":"The color of a fire truck"}]', '[{"text":"big"},{"text":"small"},{"text":"red"}]', 'big, small, red. Say each word clearly.', true),
(10, 'intermediate', 'Word Reading: Colors', 'Read color words', '[{"word":"blue","phonetic":"/bluː/","meaning":"The color of the sky"},{"word":"green","phonetic":"/ɡriːn/","meaning":"The color of grass"},{"word":"yellow","phonetic":"/ˈjeloʊ/","meaning":"The color of the sun"}]', '[{"text":"blue"},{"text":"green"},{"text":"yellow"}]', 'blue, green, yellow. Say each word clearly.', true),
(11, 'intermediate', 'Word Review: Pronouns 1', 'Review pronoun words', '[]', '[{"text":"I am here."},{"text":"You are kind."},{"text":"We play together."}]', 'I am here. You are kind. We play together.', true),
(12, 'intermediate', 'Word Review: Pronouns 2', 'Review personal pronouns', '[]', '[{"text":"He runs fast."},{"text":"She reads books."},{"text":"It is small."}]', 'He runs fast. She reads books. It is small.', true),
(13, 'intermediate', 'Word Review: Action Words 1', 'Review action verbs', '[]', '[{"text":"I run fast."},{"text":"Jump high!"},{"text":"Walk slowly."}]', 'I run fast. Jump high! Walk slowly.', true),
(14, 'intermediate', 'Word Review: Action Words 2', 'Review daily verbs', '[]', '[{"text":"I eat rice."},{"text":"Drink water."},{"text":"Time to sleep."}]', 'I eat rice. Drink water. Time to sleep.', true),
(15, 'intermediate', 'Word Review: Action Words 3', 'Review learning verbs', '[]', '[{"text":"Let us play."},{"text":"I read a book."},{"text":"Write your name."}]', 'Let us play. I read a book. Write your name.', true),
(16, 'intermediate', 'Word Review: Animals', 'Review animal words', '[]', '[{"text":"The cat sits."},{"text":"The dog barks."},{"text":"A bird sings."}]', 'The cat sits. The dog barks. A bird sings.', true),
(17, 'intermediate', 'Word Review: Toys', 'Review toy words', '[]', '[{"text":"Kick the ball."},{"text":"My toy is red."},{"text":"The car is fast."}]', 'Kick the ball. My toy is red. The car is fast.', true),
(18, 'intermediate', 'Word Review: School Items', 'Review school words', '[]', '[{"text":"Open the book."},{"text":"Use a pen."},{"text":"Pack your bag."}]', 'Open the book. Use a pen. Pack your bag.', true),
(19, 'intermediate', 'Word Review: Adjectives', 'Review descriptive words', '[]', '[{"text":"A big house."},{"text":"A small ant."},{"text":"A red rose."}]', 'A big house. A small ant. A red rose.', true),
(20, 'intermediate', 'Word Review: Colors', 'Review color words', '[]', '[{"text":"Blue sky."},{"text":"Green grass."},{"text":"Yellow sun."}]', 'Blue sky. Green grass. Yellow sun.', true),
(21, 'intermediate', 'Word Mastery: Pronouns 1', 'Master pronouns', '[]', '[{"text":"I like you."},{"text":"You and I play."},{"text":"We are friends."}]', 'I like you. We are friends.', true),
(22, 'intermediate', 'Word Mastery: Pronouns 2', 'Master pronouns', '[]', '[{"text":"He is tall."},{"text":"She is smart."},{"text":"It is round."}]', 'He is tall. She is smart.', true),
(23, 'intermediate', 'Word Mastery: Actions 1', 'Master action words', '[]', '[{"text":"Run to the park."},{"text":"Jump over it."},{"text":"Walk with me."}]', 'Run to the park. Walk with me.', true),
(24, 'intermediate', 'Word Mastery: Actions 2', 'Master daily verbs', '[]', '[{"text":"Eat your food."},{"text":"Drink some milk."},{"text":"Go to sleep."}]', 'Eat your food. Go to sleep.', true),
(25, 'intermediate', 'Word Mastery: Actions 3', 'Master learning verbs', '[]', '[{"text":"Play outside."},{"text":"Read this story."},{"text":"Write a letter."}]', 'Play outside. Write a letter.', true),
(26, 'intermediate', 'Word Mastery: Animals', 'Master animal vocab', '[]', '[{"text":"My cat is soft."},{"text":"The dog is big."},{"text":"A bird can fly."}]', 'My cat is soft. A bird can fly.', true),
(27, 'intermediate', 'Word Mastery: Toys', 'Master toy vocab', '[]', '[{"text":"Throw the ball."},{"text":"Share your toy."},{"text":"Drive the car."}]', 'Throw the ball. Drive the car.', true),
(28, 'intermediate', 'Word Mastery: School', 'Master school vocab', '[]', '[{"text":"Read the book."},{"text":"Write with a pen."},{"text":"Carry your bag."}]', 'Read the book. Carry your bag.', true),
(29, 'intermediate', 'Word Mastery: Describing 1', 'Master adjectives', '[]', '[{"text":"The big ball."},{"text":"A small cup."},{"text":"A red hat."}]', 'The big ball. A red hat.', true),
(30, 'intermediate', 'Word Mastery: Describing 2', 'Master colors', '[]', '[{"text":"A blue pen."},{"text":"A green leaf."},{"text":"A yellow bus."}]', 'A blue pen. A yellow bus.', true),
(31, 'intermediate', 'Phrase Reading: Big Dog', 'Read two-word phrases', '[]', '[{"text":"big dog"}]', 'big dog.', true),
(32, 'intermediate', 'Phrase Reading: Red Ball', 'Read phrases', '[]', '[{"text":"red ball"}]', 'red ball.', true),
(33, 'intermediate', 'Phrase Reading: Blue Car', 'Read phrases', '[]', '[{"text":"blue car"}]', 'blue car.', true),
(34, 'intermediate', 'Phrase Reading: Small Cat', 'Read phrases', '[]', '[{"text":"small cat"}]', 'small cat.', true),
(35, 'intermediate', 'Phrase Reading: Happy Boy', 'Read phrases', '[]', '[{"text":"happy boy"}]', 'happy boy.', true),
(36, 'intermediate', 'Phrase Reading: Green Tree', 'Read phrases', '[]', '[{"text":"green tree"}]', 'green tree.', true),
(37, 'intermediate', 'Phrase Reading: Fast Car', 'Read phrases', '[]', '[{"text":"fast car"}]', 'fast car.', true),
(38, 'intermediate', 'Phrase Reading: Yellow Sun', 'Read phrases', '[]', '[{"text":"yellow sun"}]', 'yellow sun.', true),
(39, 'intermediate', 'Phrase Reading: Hot Food', 'Read phrases', '[]', '[{"text":"hot food"}]', 'hot food.', true),
(40, 'intermediate', 'Phrase Reading: Cold Water', 'Read phrases', '[]', '[{"text":"cold water"}]', 'cold water.', true),
(41, 'intermediate', 'Phrase Review: Big Dog', 'Review phrases', '[]', '[{"text":"big dog"},{"text":"a big dog"},{"text":"I see a big dog."}]', 'big dog. I see a big dog.', true),
(42, 'intermediate', 'Phrase Review: Red Ball', 'Review phrases', '[]', '[{"text":"red ball"},{"text":"a red ball"},{"text":"I have a red ball."}]', 'red ball. I have a red ball.', true),
(43, 'intermediate', 'Phrase Review: Blue Car', 'Review phrases', '[]', '[{"text":"blue car"},{"text":"a blue car"},{"text":"The blue car is fast."}]', 'blue car. The blue car is fast.', true),
(44, 'intermediate', 'Phrase Review: Small Cat', 'Review phrases', '[]', '[{"text":"small cat"},{"text":"a small cat"},{"text":"The small cat sleeps."}]', 'small cat. The small cat sleeps.', true),
(45, 'intermediate', 'Phrase Review: Happy Boy', 'Review phrases', '[]', '[{"text":"happy boy"},{"text":"a happy boy"},{"text":"The happy boy plays."}]', 'happy boy. The happy boy plays.', true),
(46, 'intermediate', 'Phrase Review: Green Tree', 'Review phrases', '[]', '[{"text":"green tree"},{"text":"a green tree"},{"text":"The green tree is tall."}]', 'green tree. Tall.', true),
(47, 'intermediate', 'Phrase Review: Fast Car', 'Review phrases', '[]', '[{"text":"fast car"},{"text":"a fast car"},{"text":"Look at the fast car!"}]', 'fast car. Look!', true),
(48, 'intermediate', 'Phrase Review: Yellow Sun', 'Review phrases', '[]', '[{"text":"yellow sun"},{"text":"the yellow sun"},{"text":"The yellow sun is bright."}]', 'yellow sun. Bright.', true),
(49, 'intermediate', 'Phrase Review: Hot Food', 'Review phrases', '[]', '[{"text":"hot food"},{"text":"the hot food"},{"text":"Be careful with hot food."}]', 'hot food. Be careful.', true),
(50, 'intermediate', 'Phrase Review: Cold Water', 'Review phrases', '[]', '[{"text":"cold water"},{"text":"some cold water"},{"text":"I drink cold water."}]', 'cold water. I drink it.', true),
(51, 'intermediate', 'Phrase Mastery: Animals', 'Master phrases', '[]', '[{"text":"big dog"},{"text":"small cat"},{"text":"The big dog and the small cat."}]', 'big dog, small cat.', true),
(52, 'intermediate', 'Phrase Mastery: Colors', 'Master phrases', '[]', '[{"text":"red ball"},{"text":"blue car"},{"text":"The red ball and the blue car."}]', 'red ball, blue car.', true),
(53, 'intermediate', 'Phrase Mastery: Nature', 'Master phrases', '[]', '[{"text":"green tree"},{"text":"yellow sun"}]', 'green tree, yellow sun.', true),
(54, 'intermediate', 'Phrase Mastery: Food', 'Master phrases', '[]', '[{"text":"hot food"},{"text":"cold water"}]', 'hot food, cold water.', true),
(55, 'intermediate', 'Phrase Mastery: People', 'Master phrases', '[]', '[{"text":"happy boy"},{"text":"The happy boy runs fast."}]', 'happy boy runs fast.', true),
(56, 'intermediate', 'Phrase Combo: Set 1', 'Combine phrases', '[]', '[{"text":"big red ball"},{"text":"small blue car"},{"text":"happy green bird"}]', 'big red ball. small blue car.', true),
(57, 'intermediate', 'Phrase Combo: Set 2', 'Combine phrases', '[]', '[{"text":"fast yellow car"},{"text":"hot red food"},{"text":"cold blue water"}]', 'fast yellow car.', true),
(58, 'intermediate', 'Phrase Combo: Set 3', 'Three-word phrases', '[]', '[{"text":"the big dog"},{"text":"a small cat"},{"text":"my red ball"}]', 'the big dog. my red ball.', true),
(59, 'intermediate', 'Phrase Combo: Set 4', 'Three-word phrases', '[]', '[{"text":"her blue book"},{"text":"his green pen"},{"text":"our yellow bag"}]', 'her blue book. our yellow bag.', true),
(60, 'intermediate', 'Phrase Combo: Set 5', 'Three-word mastery', '[]', '[{"text":"a happy boy"},{"text":"the fast car"},{"text":"some hot food"}]', 'a happy boy. the fast car.', true),
(61, 'intermediate', 'Sentence Reading: I See', 'Read 4-word sentences', '[]', '[{"text":"I see a cat."}]', 'I see a cat.', true),
(62, 'intermediate', 'Sentence Reading: I See 2', 'Read sentences', '[]', '[{"text":"I see a dog."}]', 'I see a dog.', true),
(63, 'intermediate', 'Sentence Reading: I Have', 'Read sentences', '[]', '[{"text":"I have a ball."}]', 'I have a ball.', true),
(64, 'intermediate', 'Sentence Reading: Dog Runs', 'Read action sentences', '[]', '[{"text":"The dog runs."}]', 'The dog runs.', true),
(65, 'intermediate', 'Sentence Reading: Boy Jumps', 'Read action sentences', '[]', '[{"text":"The boy jumps."}]', 'The boy jumps.', true),
(66, 'intermediate', 'Sentence Reading: Cat Sleeps', 'Read sentences', '[]', '[{"text":"The cat sleeps."}]', 'The cat sleeps.', true),
(67, 'intermediate', 'Sentence Reading: Bird Flies', 'Read sentences', '[]', '[{"text":"The bird flies."}]', 'The bird flies.', true),
(68, 'intermediate', 'Sentence Reading: She Reads', 'Read sentences', '[]', '[{"text":"She reads a book."}]', 'She reads a book.', true),
(69, 'intermediate', 'Sentence Reading: He Drinks', 'Read sentences', '[]', '[{"text":"He drinks water."}]', 'He drinks water.', true),
(70, 'intermediate', 'Sentence Reading: The Car', 'Read sentences', '[]', '[{"text":"The car is red."}]', 'The car is red.', true),
(71, 'intermediate', 'Sentence Reading: The Sky', 'Read sentences', '[]', '[{"text":"The sky is blue."}]', 'The sky is blue.', true),
(72, 'intermediate', 'Sentence Reading: The Tree', 'Read sentences', '[]', '[{"text":"The tree is tall."}]', 'The tree is tall.', true),
(73, 'intermediate', 'Sentence Review: See 1', 'Review sentences', '[]', '[{"text":"I see a cat."},{"text":"I see a big cat."}]', 'I see a cat. I see a big cat.', true),
(74, 'intermediate', 'Sentence Review: See 2', 'Review sentences', '[]', '[{"text":"I see a dog."},{"text":"I see a small dog."}]', 'I see a dog.', true),
(75, 'intermediate', 'Sentence Review: Have', 'Review sentences', '[]', '[{"text":"I have a ball."},{"text":"I have a red ball."}]', 'I have a ball.', true),
(76, 'intermediate', 'Sentence Review: Dog', 'Review sentences', '[]', '[{"text":"The dog runs."},{"text":"The dog runs fast."}]', 'The dog runs fast.', true),
(77, 'intermediate', 'Sentence Review: Boy', 'Review sentences', '[]', '[{"text":"The boy jumps."},{"text":"The boy jumps high."}]', 'The boy jumps high.', true),
(78, 'intermediate', 'Sentence Review: Cat', 'Review sentences', '[]', '[{"text":"The cat sleeps."},{"text":"The cat sleeps on the bed."}]', 'The cat sleeps on the bed.', true),
(79, 'intermediate', 'Sentence Review: Bird', 'Review sentences', '[]', '[{"text":"The bird flies."},{"text":"The bird flies in the sky."}]', 'The bird flies in the sky.', true),
(80, 'intermediate', 'Sentence Review: She', 'Review sentences', '[]', '[{"text":"She reads a book."},{"text":"She reads a big book."}]', 'She reads a big book.', true),
(81, 'intermediate', 'Sentence Review: He', 'Review sentences', '[]', '[{"text":"He drinks water."},{"text":"He drinks cold water."}]', 'He drinks cold water.', true),
(82, 'intermediate', 'Sentence Review: Car', 'Review sentences', '[]', '[{"text":"The car is red."},{"text":"The car is big and red."}]', 'The car is big and red.', true),
(83, 'intermediate', 'Sentence Review: Sky', 'Review sentences', '[]', '[{"text":"The sky is blue."},{"text":"The sky is very blue today."}]', 'The sky is very blue.', true),
(84, 'intermediate', 'Sentence Review: Tree', 'Review sentences', '[]', '[{"text":"The tree is tall."},{"text":"The green tree is tall."}]', 'The green tree is tall.', true),
(85, 'intermediate', 'Sentence Mastery: See', 'Master sentences', '[]', '[{"text":"I see a cat."},{"text":"I see a big red cat."},{"text":"Do you see the cat?"}]', 'I see a big red cat.', true),
(86, 'intermediate', 'Sentence Mastery: Dog', 'Master sentences', '[]', '[{"text":"I see a dog."},{"text":"The dog is brown."},{"text":"The dog runs to me."}]', 'The dog runs to me.', true),
(87, 'intermediate', 'Sentence Mastery: Ball', 'Master sentences', '[]', '[{"text":"I have a ball."},{"text":"My ball is red."},{"text":"Throw the ball to me."}]', 'Throw the ball to me.', true),
(88, 'intermediate', 'Sentence Mastery: Run', 'Master sentences', '[]', '[{"text":"The dog runs."},{"text":"I can run fast."},{"text":"We run and play."}]', 'We run and play.', true),
(89, 'intermediate', 'Sentence Mastery: Jump', 'Master sentences', '[]', '[{"text":"The boy jumps."},{"text":"Jump over the ball."},{"text":"She can jump high."}]', 'She can jump high.', true),
(90, 'intermediate', 'Sentence Mastery: Sleep', 'Master sentences', '[]', '[{"text":"The cat sleeps."},{"text":"Time to sleep now."},{"text":"The baby sleeps well."}]', 'The baby sleeps well.', true),
(91, 'intermediate', 'Question: What Is This?', 'Answer what questions', '[]', '[{"text":"What is this?"},{"text":"This is a ball."}]', 'What is this? This is a ball.', true),
(92, 'intermediate', 'Question: Where?', 'Answer where questions', '[]', '[{"text":"Where is the cat?"},{"text":"The cat is on the bed."}]', 'Where is the cat?', true),
(93, 'intermediate', 'Question: Who?', 'Answer who questions', '[]', '[{"text":"Who is this?"},{"text":"This is my friend."}]', 'Who is this?', true),
(94, 'intermediate', 'Question: What Color?', 'Answer color questions', '[]', '[{"text":"What color is the ball?"},{"text":"The ball is red."}]', 'What color is the ball?', true),
(95, 'intermediate', 'Question: What See?', 'Answer observation questions', '[]', '[{"text":"What do you see?"},{"text":"I see a bird."}]', 'What do you see?', true),
(96, 'intermediate', 'Question Review: What', 'Review what questions', '[]', '[{"text":"What is this?"},{"text":"This is a pen."}]', 'What is this? A pen.', true),
(97, 'intermediate', 'Question Review: Where', 'Review where questions', '[]', '[{"text":"Where is the cat?"},{"text":"Under the table."}]', 'Where is the cat?', true),
(98, 'intermediate', 'Question Review: Who', 'Review who questions', '[]', '[{"text":"Who is this?"},{"text":"This is my teacher."}]', 'Who is this?', true),
(99, 'intermediate', 'Question Review: Color', 'Review color questions', '[]', '[{"text":"What color is the ball?"},{"text":"The ball is blue."}]', 'What color? Blue.', true),
(100, 'intermediate', 'Question Review: See', 'Review questions', '[]', '[{"text":"What do you see?"},{"text":"I see a tree."}]', 'What do you see?', true),
(101, 'intermediate', 'Question Practice: What 2', 'Practice questions', '[]', '[{"text":"What is this?"},{"text":"This is a cup."}]', 'What is this? A cup.', true),
(102, 'intermediate', 'Question Practice: Where 2', 'Practice questions', '[]', '[{"text":"Where is the cat?"},{"text":"In the garden."}]', 'Where is the cat?', true),
(103, 'intermediate', 'Question Practice: Who 2', 'Practice questions', '[]', '[{"text":"Who is this?"},{"text":"This is my mother."}]', 'Who is this?', true),
(104, 'intermediate', 'Question Practice: Color 2', 'Practice questions', '[]', '[{"text":"What color is the ball?"},{"text":"Green."}]', 'What color? Green.', true),
(105, 'intermediate', 'Question Practice: See 2', 'Practice questions', '[]', '[{"text":"What do you see?"},{"text":"I see a flower."}]', 'What do you see?', true),
(106, 'intermediate', 'Question Mastery: What', 'Master questions', '[]', '[{"text":"What is this?"},{"text":"This is my bag."}]', 'What is this? My bag.', true),
(107, 'intermediate', 'Question Mastery: Where', 'Master questions', '[]', '[{"text":"Where is the cat?"},{"text":"On the chair."}]', 'Where is the cat?', true),
(108, 'intermediate', 'Question Mastery: Who', 'Master questions', '[]', '[{"text":"Who is this?"},{"text":"My father."}]', 'Who is this?', true),
(109, 'intermediate', 'Question Mastery: Color', 'Master questions', '[]', '[{"text":"What color is the ball?"},{"text":"Yellow."}]', 'What color? Yellow.', true),
(110, 'intermediate', 'Question Mastery: See', 'Master questions', '[]', '[{"text":"What do you see?"},{"text":"I see a house."}]', 'What do you see?', true),
(111, 'intermediate', 'Question Combo: What', 'Combined practice', '[]', '[{"text":"What is this?"},{"text":"A toy car. It is red."}]', 'What is this? A toy car.', true),
(112, 'intermediate', 'Question Combo: Where', 'Combined practice', '[]', '[{"text":"Where is the cat?"},{"text":"On the sofa, sleeping."}]', 'Where is the cat?', true),
(113, 'intermediate', 'Question Combo: Who', 'Combined practice', '[]', '[{"text":"Who is this?"},{"text":"My sister. She is kind."}]', 'Who is this?', true),
(114, 'intermediate', 'Question Combo: Color', 'Combined practice', '[]', '[{"text":"What color?"},{"text":"Orange. I like orange."}]', 'What color? Orange.', true),
(115, 'intermediate', 'Question Combo: See', 'Combined practice', '[]', '[{"text":"What do you see?"},{"text":"A river. It is big."}]', 'What do you see?', true),
(116, 'intermediate', 'Question Fluency: What', 'Fluent answers', '[]', '[{"text":"What is this?"},{"text":"A clock. It is round."}]', 'What is this? A clock.', true),
(117, 'intermediate', 'Question Fluency: Where', 'Fluent answers', '[]', '[{"text":"Where is the cat?"},{"text":"Behind the door."}]', 'Behind the door.', true),
(118, 'intermediate', 'Question Fluency: Who', 'Fluent answers', '[]', '[{"text":"Who is this?"},{"text":"My brother."}]', 'My brother.', true),
(119, 'intermediate', 'Question Fluency: Color', 'Fluent answers', '[]', '[{"text":"What color?"},{"text":"Pink."}]', 'Pink.', true),
(120, 'intermediate', 'Question Fluency: See', 'Fluent answers', '[]', '[{"text":"What do you see?"},{"text":"A rainbow! Many colors."}]', 'A rainbow!', true),
(121, 'intermediate', 'Story: Tom''s Dog', 'Read a short story', '[]', '[{"text":"Tom has a dog."},{"text":"The dog runs fast."},{"text":"Tom plays with the dog."}]', 'Tom has a dog. The dog runs fast.', true),
(122, 'intermediate', 'Story: Riya''s Book', 'Read a story', '[]', '[{"text":"Riya has a book."},{"text":"She reads the book."},{"text":"She learns new words."}]', 'Riya has a book. She learns new words.', true),
(123, 'intermediate', 'Story: The Cat', 'Read a story', '[]', '[{"text":"A cat sees milk."},{"text":"The cat drinks milk."},{"text":"The cat sleeps."}]', 'A cat sees milk. The cat sleeps.', true),
(124, 'intermediate', 'Story Review: Tom 2', 'Re-read story', '[]', '[{"text":"Tom has a dog."},{"text":"The dog runs fast."},{"text":"They are happy."}]', 'Tom has a dog. They are happy.', true),
(125, 'intermediate', 'Story Review: Riya 2', 'Re-read story', '[]', '[{"text":"Riya has a book."},{"text":"She reads the book."},{"text":"Riya is happy."}]', 'Riya reads. She is happy.', true),
(126, 'intermediate', 'Story Review: Cat 2', 'Re-read story', '[]', '[{"text":"A cat sees milk."},{"text":"The cat drinks milk."},{"text":"The cat is full."}]', 'The cat drinks milk. Full.', true),
(127, 'intermediate', 'Story Fluency: Tom 3', 'Fluent reading', '[]', '[{"text":"Tom has a dog."},{"text":"They run in the park."},{"text":"They are best friends."}]', 'Tom and his dog run in the park.', true),
(128, 'intermediate', 'Story Fluency: Riya 3', 'Fluent reading', '[]', '[{"text":"Riya reads every day."},{"text":"She knows many words."},{"text":"Riya is smart."}]', 'Riya reads every day. She is smart.', true),
(129, 'intermediate', 'Story Fluency: Cat 3', 'Fluent reading', '[]', '[{"text":"The cat drinks all the milk."},{"text":"The cat is happy."},{"text":"The cat sleeps."}]', 'The cat is happy and sleeps.', true),
(130, 'intermediate', 'Story Expression: Tom 4', 'Read with expression', '[]', '[{"text":"Tom has a big dog."},{"text":"The dog runs very fast."},{"text":"They are best friends!"}]', 'Tom has a big dog. Best friends!', true),
(131, 'intermediate', 'Story Expression: Riya 4', 'Read with expression', '[]', '[{"text":"Riya loves to read."},{"text":"She reads a new book every week."},{"text":"Reading makes her happy!"}]', 'Riya loves to read!', true),
(132, 'intermediate', 'Story Expression: Cat 4', 'Read with expression', '[]', '[{"text":"The cat sees a bowl of milk."},{"text":"She drinks slowly."},{"text":"Very happy!"}]', 'The cat is very happy!', true),
(133, 'intermediate', 'Story Mastery: Tom 5', 'Master story', '[]', '[{"text":"Tom has a big brown dog."},{"text":"Every morning they run."},{"text":"Best of friends!"}]', 'Tom and his big brown dog.', true),
(134, 'intermediate', 'Story Mastery: Riya 5', 'Master story', '[]', '[{"text":"Riya has many books."},{"text":"She reads before bed."},{"text":"She wants to be a teacher."}]', 'Riya wants to be a teacher.', true),
(135, 'intermediate', 'Story Mastery: Cat 5', 'Master story', '[]', '[{"text":"The cat drinks milk."},{"text":"The cat sleeps on the mat."},{"text":"Full and happy!"}]', 'The cat is full and happy!', true),
(136, 'intermediate', 'Story: Rex', 'New story', '[]', '[{"text":"Tom has a dog named Rex."},{"text":"Rex runs very fast!"},{"text":"They love the park!"}]', 'Tom and Rex love the park!', true),
(137, 'intermediate', 'Story: New Book', 'New story', '[]', '[{"text":"Riya found a new book."},{"text":"She reads it to her brother."},{"text":"They both laugh and learn."}]', 'Riya reads to her brother.', true),
(138, 'intermediate', 'Story: Hungry Cat', 'New story', '[]', '[{"text":"The little cat is hungry."},{"text":"She drinks milk."},{"text":"Now she is full and sleepy."}]', 'The hungry cat is now full.', true),
(139, 'intermediate', 'Story: Park Day', 'Park story', '[]', '[{"text":"The children go to the park."},{"text":"They run and play."},{"text":"It is a fun day!"}]', 'Fun day at the park!', true),
(140, 'intermediate', 'Story: School', 'School story', '[]', '[{"text":"It is time for school."},{"text":"They read and write."},{"text":"They love to learn!"}]', 'Time for school!', true),
(141, 'intermediate', 'Story: Rain', 'Weather story', '[]', '[{"text":"It is raining today."},{"text":"The cat stays inside."},{"text":"The sun comes out."}]', 'Rain then sun!', true),
(142, 'intermediate', 'Story: Market', 'Shopping story', '[]', '[{"text":"Mom goes to the market."},{"text":"She buys fruits."},{"text":"We eat together."}]', 'Mom buys fruits at the market.', true),
(143, 'intermediate', 'Story: Garden', 'Garden story', '[]', '[{"text":"Dad plants a tree."},{"text":"The tree grows tall."},{"text":"We water it every day."}]', 'Dad plants a tree. We water it.', true),
(144, 'intermediate', 'Story: Birthday', 'Celebration story', '[]', '[{"text":"Today is my birthday!"},{"text":"I get a cake."},{"text":"We have so much fun!"}]', 'Happy birthday! So much fun!', true),
(145, 'intermediate', 'Story: Beach', 'Travel story', '[]', '[{"text":"We go to the beach."},{"text":"We play in the sand."},{"text":"It is a happy day."}]', 'Happy day at the beach!', true),
(146, 'intermediate', 'Story: Night', 'Bedtime story', '[]', '[{"text":"The moon is bright."},{"text":"Stars shine in the sky."},{"text":"Good night, everyone!"}]', 'Good night!', true),
(147, 'intermediate', 'Story: Friends', 'Friendship story', '[]', '[{"text":"Tom and Riya are friends."},{"text":"They play every day."},{"text":"Friends are the best!"}]', 'Friends are the best!', true),
(148, 'intermediate', 'Story: Breakfast', 'Morning story', '[]', '[{"text":"I wake up early."},{"text":"Mom makes breakfast."},{"text":"Time to go to school!"}]', 'Good morning! Time for school.', true),
(149, 'intermediate', 'Story: Pets', 'Pet story', '[]', '[{"text":"I have a cat and a dog."},{"text":"The cat is small, the dog is big."},{"text":"I love them both!"}]', 'I love my pets!', true),
(150, 'intermediate', 'Story: Colors', 'Description story', '[]', '[{"text":"Flowers are red and yellow."},{"text":"The sky is blue."},{"text":"The world is beautiful!"}]', 'The world is beautiful!', true),
(151, 'intermediate', 'Picture Talk: Objects 1', 'Describe objects', '[]', '[{"text":"I see a ball."},{"text":"The ball is red."},{"text":"It is on the floor."}]', 'Describe what you see.', true),
(152, 'intermediate', 'Picture Talk: Objects 2', 'Describe objects', '[]', '[{"text":"I see a book."},{"text":"The book is blue."},{"text":"It is on the table."}]', 'Describe what you see.', true),
(153, 'intermediate', 'Picture Talk: Animals 1', 'Describe animals', '[]', '[{"text":"I see a cat."},{"text":"The cat is white."},{"text":"It sits on a chair."}]', 'Describe what you see.', true),
(154, 'intermediate', 'Picture Talk: Animals 2', 'Describe animals', '[]', '[{"text":"I see a dog."},{"text":"The dog is brown."},{"text":"It is running."}]', 'Describe what you see.', true),
(155, 'intermediate', 'Picture Talk: People 1', 'Describe people', '[]', '[{"text":"I see a boy."},{"text":"He plays with a ball."},{"text":"He looks happy."}]', 'Describe what you see.', true),
(156, 'intermediate', 'Picture Talk: People 2', 'Describe people', '[]', '[{"text":"I see a girl."},{"text":"She reads a book."},{"text":"She is under a tree."}]', 'Describe what you see.', true),
(157, 'intermediate', 'Picture Talk: Places 1', 'Describe places', '[]', '[{"text":"I see a park."},{"text":"Trees and flowers."},{"text":"Children are playing."}]', 'Describe what you see.', true),
(158, 'intermediate', 'Picture Talk: Places 2', 'Describe scenes', '[]', '[{"text":"I see a school."},{"text":"Students walk in."},{"text":"The building is big."}]', 'Describe what you see.', true),
(159, 'intermediate', 'Picture Talk: Food 1', 'Describe food', '[]', '[{"text":"I see fruit."},{"text":"Apples and bananas."},{"text":"They look fresh."}]', 'Describe what you see.', true),
(160, 'intermediate', 'Picture Talk: Food 2', 'Describe meals', '[]', '[{"text":"I see rice."},{"text":"There is curry."},{"text":"It looks delicious."}]', 'Describe what you see.', true),
(161, 'intermediate', 'Picture Talk: Weather 1', 'Describe weather', '[]', '[{"text":"The sun shines."},{"text":"The sky is blue."},{"text":"Sunny day!"}]', 'Describe the weather.', true),
(162, 'intermediate', 'Picture Talk: Weather 2', 'Describe weather', '[]', '[{"text":"It is raining."},{"text":"People have umbrellas."},{"text":"Roads are wet."}]', 'Describe the weather.', true),
(163, 'intermediate', 'Picture Talk: Home 1', 'Describe home', '[]', '[{"text":"I see a house."},{"text":"Red door."},{"text":"A garden outside."}]', 'Describe what you see.', true),
(164, 'intermediate', 'Picture Talk: Home 2', 'Describe rooms', '[]', '[{"text":"I see a bedroom."},{"text":"A bed and table."},{"text":"A lamp is on the table."}]', 'Describe what you see.', true),
(165, 'intermediate', 'Picture Talk: Transport 1', 'Describe vehicles', '[]', '[{"text":"I see a bus."},{"text":"It is yellow."},{"text":"People get on."}]', 'Describe what you see.', true),
(166, 'intermediate', 'Picture Talk: Transport 2', 'Describe transport', '[]', '[{"text":"I see a bicycle."},{"text":"A boy rides it."},{"text":"Going to school."}]', 'Describe what you see.', true),
(167, 'intermediate', 'Picture Talk: Nature 1', 'Describe nature', '[]', '[{"text":"I see a river."},{"text":"Water is clear."},{"text":"Fish swim."}]', 'Describe what you see.', true),
(168, 'intermediate', 'Picture Talk: Nature 2', 'Describe nature', '[]', '[{"text":"I see mountains."},{"text":"Very tall."},{"text":"Snow on top."}]', 'Describe what you see.', true),
(169, 'intermediate', 'Picture Talk: Combo 1', 'Complex description', '[]', '[{"text":"A family at the park."},{"text":"Children play."},{"text":"Parents sit."}]', 'Describe the scene.', true),
(170, 'intermediate', 'Picture Talk: Combo 2', 'Complex description', '[]', '[{"text":"A busy market."},{"text":"People buy fruits."},{"text":"Very crowded."}]', 'Describe the scene.', true),
(171, 'intermediate', 'Narrate: My Day', 'Tell a story about your day', '[]', '[{"text":"I wake up."},{"text":"I eat breakfast."},{"text":"I go to school."},{"text":"I play at home."}]', 'Tell a story about your day.', true),
(172, 'intermediate', 'Narrate: My Pet', 'Tell a pet story', '[]', '[{"text":"I have a pet cat."},{"text":"Her name is Luna."},{"text":"She plays with yarn."},{"text":"I love her."}]', 'Tell a story about a pet.', true),
(173, 'intermediate', 'Narrate: The Park', 'Tell a park story', '[]', '[{"text":"I go to the park."},{"text":"Children play."},{"text":"I swing."},{"text":"It is fun!"}]', 'Tell a story about the park.', true),
(174, 'intermediate', 'Narrate: My Friend', 'Tell a friendship story', '[]', '[{"text":"My friend is kind."},{"text":"We play together."},{"text":"We share food."},{"text":"I am happy."}]', 'Tell a story about your friend.', true),
(175, 'intermediate', 'Narrate: Rainy Day', 'Tell a rainy day story', '[]', '[{"text":"It is raining."},{"text":"I stay inside."},{"text":"I read a book."},{"text":"I see a rainbow!"}]', 'Tell a rainy day story.', true),
(176, 'intermediate', 'Narrate: School Day', 'Tell a school story', '[]', '[{"text":"I go to school."},{"text":"I learn new things."},{"text":"I play with friends."},{"text":"School is fun!"}]', 'Tell a school day story.', true),
(177, 'intermediate', 'Narrate: Family', 'Tell a family story', '[]', '[{"text":"My family is big."},{"text":"We eat dinner."},{"text":"We talk and laugh."},{"text":"I love my family."}]', 'Tell a family story.', true),
(178, 'intermediate', 'Narrate: Adventure', 'Tell an adventure story', '[]', '[{"text":"I find a treasure map!"},{"text":"I follow the map."},{"text":"I find a box."},{"text":"Inside is a toy!"}]', 'Tell an adventure story!', true),
(179, 'intermediate', 'Narrate: Dream', 'Tell a dream story', '[]', '[{"text":"I had a dream."},{"text":"I could fly!"},{"text":"I flew over the city."},{"text":"It was amazing!"}]', 'Tell a dream story.', true),
(180, 'intermediate', 'Narrate: Graduation!', 'Level 2 complete!', '[]', '[{"text":"I finish Level 2!"},{"text":"I can read stories."},{"text":"I speak in sentences."},{"text":"Ready for Level 3!"}]', 'Congratulations! You finished Level 2!', true);
