
-- Phase 2: Letter-Sound Connection (Days 31-60)
UPDATE lessons SET title = 'Letter A Meets Sound /a/', description = 'Connect the letter A with the /a/ sound you already know', vocabulary = '[{"word":"A","phonetic":"/eɪ/","meaning":"The letter A"},{"word":"apple","phonetic":"/æ/","meaning":"A starts the /a/ sound"},{"word":"arrow","phonetic":"/ˈæroʊ/","meaning":"Points the way"}]'::jsonb, sentences = '[{"text":"A is for apple","tip":"The letter A makes the /a/ sound"},{"text":"I see the letter A","tip":"Can you write it?"}]'::jsonb, read_aloud_text = 'Meet the letter A! It makes the /a/ sound, just like in apple!' WHERE level = 'beginner' AND day_number = 31;

UPDATE lessons SET title = 'Letter B Meets Sound /b/', description = 'Connect the letter B with the /b/ sound', vocabulary = '[{"word":"B","phonetic":"/biː/","meaning":"The letter B"},{"word":"ball","phonetic":"/b/","meaning":"B starts ball"},{"word":"bird","phonetic":"/bɜːrd/","meaning":"Flies in the sky"}]'::jsonb, sentences = '[{"text":"B is for ball","tip":"The letter B makes the /b/ sound"},{"text":"I see the letter B","tip":"Can you trace it?"}]'::jsonb, read_aloud_text = 'Meet the letter B! It makes the /b/ sound, like in ball and bird!' WHERE level = 'beginner' AND day_number = 32;

UPDATE lessons SET title = 'Letter C Meets Sound /k/', description = 'Connect the letter C with the /k/ sound', vocabulary = '[{"word":"C","phonetic":"/siː/","meaning":"The letter C"},{"word":"cat","phonetic":"/k/","meaning":"C starts cat"},{"word":"car","phonetic":"/kɑːr/","meaning":"Drives on roads"}]'::jsonb, sentences = '[{"text":"C is for cat","tip":"C often makes the /k/ sound"},{"text":"I can see C","tip":"Trace the letter"}]'::jsonb, read_aloud_text = 'Meet the letter C! It makes the /k/ sound, like in cat and car!' WHERE level = 'beginner' AND day_number = 33;

UPDATE lessons SET title = 'Letter D Meets Sound /d/', description = 'Connect the letter D with the /d/ sound', vocabulary = '[{"word":"D","phonetic":"/diː/","meaning":"The letter D"},{"word":"dog","phonetic":"/d/","meaning":"D starts dog"},{"word":"door","phonetic":"/dɔːr/","meaning":"You open it"}]'::jsonb, sentences = '[{"text":"D is for dog","tip":"D makes the /d/ sound"},{"text":"Open the door","tip":"Door starts with D"}]'::jsonb, read_aloud_text = 'Meet the letter D! It makes the /d/ sound, like in dog and door!' WHERE level = 'beginner' AND day_number = 34;

UPDATE lessons SET title = 'Letter E Meets Sound /e/', description = 'Connect the letter E with the /e/ sound', vocabulary = '[{"word":"E","phonetic":"/iː/","meaning":"The letter E"},{"word":"egg","phonetic":"/ɛ/","meaning":"E starts egg"},{"word":"elf","phonetic":"/ɛlf/","meaning":"A tiny magical helper"}]'::jsonb, sentences = '[{"text":"E is for egg","tip":"E makes the /e/ sound"},{"text":"The elf is small","tip":"Elf starts with E"}]'::jsonb, read_aloud_text = 'Meet the letter E! It makes the /e/ sound, like in egg and elf!' WHERE level = 'beginner' AND day_number = 35;

UPDATE lessons SET title = 'Letters F-G Connection', description = 'Connect letters F and G with their sounds', vocabulary = '[{"word":"F","phonetic":"/ɛf/","meaning":"The letter F"},{"word":"fish","phonetic":"/f/","meaning":"F starts fish"},{"word":"G","phonetic":"/dʒiː/","meaning":"The letter G"},{"word":"goat","phonetic":"/ɡ/","meaning":"G starts goat"}]'::jsonb, sentences = '[{"text":"F is for fish","tip":"F makes the /f/ sound"},{"text":"G is for goat","tip":"G makes the /g/ sound"}]'::jsonb, read_aloud_text = 'F is for fish! G is for goat! Two more letters learned!' WHERE level = 'beginner' AND day_number = 36;

UPDATE lessons SET title = 'Letters H-I Connection', description = 'Connect letters H and I with their sounds', vocabulary = '[{"word":"H","phonetic":"/eɪtʃ/","meaning":"The letter H"},{"word":"hat","phonetic":"/h/","meaning":"H starts hat"},{"word":"I","phonetic":"/aɪ/","meaning":"The letter I"},{"word":"igloo","phonetic":"/ɪ/","meaning":"I starts igloo"}]'::jsonb, sentences = '[{"text":"H is for hat","tip":"H makes the /h/ sound"},{"text":"I is for igloo","tip":"I makes the /i/ sound"}]'::jsonb, read_aloud_text = 'H is for hat! I is for igloo! You are learning so fast!' WHERE level = 'beginner' AND day_number = 37;

UPDATE lessons SET title = 'Letters J-K Connection', description = 'Connect letters J and K with their sounds', vocabulary = '[{"word":"J","phonetic":"/dʒeɪ/","meaning":"The letter J"},{"word":"jar","phonetic":"/dʒ/","meaning":"J starts jar"},{"word":"K","phonetic":"/keɪ/","meaning":"The letter K"},{"word":"kite","phonetic":"/k/","meaning":"K starts kite"}]'::jsonb, sentences = '[{"text":"J is for jar","tip":"J makes the /j/ sound"},{"text":"K is for kite","tip":"K makes the /k/ sound"}]'::jsonb, read_aloud_text = 'J is for jar! K is for kite! Flying high with letters!' WHERE level = 'beginner' AND day_number = 38;

UPDATE lessons SET title = 'Letters L-M-N Connection', description = 'Connect letters L, M, and N with their sounds', vocabulary = '[{"word":"lion","phonetic":"/l/","meaning":"L starts lion"},{"word":"moon","phonetic":"/m/","meaning":"M starts moon"},{"word":"nose","phonetic":"/n/","meaning":"N starts nose"}]'::jsonb, sentences = '[{"text":"L is for lion","tip":"L makes the /l/ sound"},{"text":"M is for moon","tip":"M makes the /m/ sound"},{"text":"N is for nose","tip":"N makes the /n/ sound"}]'::jsonb, read_aloud_text = 'L, M, N — lion, moon, nose! Three letters at once!' WHERE level = 'beginner' AND day_number = 39;

UPDATE lessons SET title = 'Letters O-P Connection', description = 'Connect letters O and P with their sounds', vocabulary = '[{"word":"O","phonetic":"/oʊ/","meaning":"The letter O"},{"word":"octopus","phonetic":"/ɒ/","meaning":"O starts octopus"},{"word":"P","phonetic":"/piː/","meaning":"The letter P"},{"word":"pen","phonetic":"/p/","meaning":"P starts pen"}]'::jsonb, sentences = '[{"text":"O is for octopus","tip":"O makes the /o/ sound"},{"text":"P is for pen","tip":"P makes the /p/ sound"}]'::jsonb, read_aloud_text = 'O is for octopus! P is for pen! You are almost halfway!' WHERE level = 'beginner' AND day_number = 40;

UPDATE lessons SET title = 'Letters Q-R-S Connection', description = 'Connect letters Q, R, and S with their sounds', vocabulary = '[{"word":"queen","phonetic":"/kw/","meaning":"Q starts queen"},{"word":"rain","phonetic":"/r/","meaning":"R starts rain"},{"word":"sun","phonetic":"/s/","meaning":"S starts sun"}]'::jsonb, sentences = '[{"text":"Q is for queen","tip":"Q makes the /kw/ sound"},{"text":"R is for rain","tip":"R makes the /r/ sound"},{"text":"S is for sun","tip":"S makes the /s/ sound"}]'::jsonb, read_aloud_text = 'Q, R, S — queen, rain, sun! Three more letters mastered!' WHERE level = 'beginner' AND day_number = 41;

UPDATE lessons SET title = 'Letters T-U-V Connection', description = 'Connect letters T, U, and V with their sounds', vocabulary = '[{"word":"tree","phonetic":"/t/","meaning":"T starts tree"},{"word":"umbrella","phonetic":"/ʌ/","meaning":"U starts umbrella"},{"word":"van","phonetic":"/v/","meaning":"V starts van"}]'::jsonb, sentences = '[{"text":"T is for tree","tip":"T makes the /t/ sound"},{"text":"U is for umbrella","tip":"U makes the /u/ sound"},{"text":"V is for van","tip":"V makes the /v/ sound"}]'::jsonb, read_aloud_text = 'T, U, V — tree, umbrella, van! Almost there!' WHERE level = 'beginner' AND day_number = 42;

UPDATE lessons SET title = 'Letters W-X-Y-Z Connection', description = 'Learn the last four letters and their sounds', vocabulary = '[{"word":"water","phonetic":"/w/","meaning":"W starts water"},{"word":"box","phonetic":"/ks/","meaning":"X in box"},{"word":"yellow","phonetic":"/j/","meaning":"Y starts yellow"},{"word":"zebra","phonetic":"/z/","meaning":"Z starts zebra"}]'::jsonb, sentences = '[{"text":"W is for water","tip":"W makes the /w/ sound"},{"text":"X says /ks/ in box","tip":"X usually comes at the end"},{"text":"Y is for yellow","tip":"Y makes the /y/ sound"},{"text":"Z is for zebra","tip":"Z makes the /z/ sound"}]'::jsonb, read_aloud_text = 'W, X, Y, Z! You know all 26 letters now! Amazing!' WHERE level = 'beginner' AND day_number = 43;

UPDATE lessons SET title = 'Alphabet Song & Review', description = 'Sing along and review all 26 letters with their sounds', vocabulary = '[{"word":"alphabet","phonetic":"/ˈælfəbɛt/","meaning":"All 26 letters"},{"word":"letters","phonetic":"/ˈlɛtərz/","meaning":"The building blocks of words"},{"word":"sounds","phonetic":"/saʊndz/","meaning":"What letters say"}]'::jsonb, sentences = '[{"text":"Sing the alphabet","tip":"A B C D E F G..."},{"text":"Every letter has a sound","tip":"You know them all!"}]'::jsonb, read_aloud_text = 'A B C D E F G, H I J K L M N O P, Q R S T U V, W X Y and Z! Now I know my ABCs!' WHERE level = 'beginner' AND day_number = 44;

UPDATE lessons SET title = 'Letter Tracing Practice', description = 'Practice tracing and saying letters A through M', vocabulary = '[{"word":"A","phonetic":"/eɪ/","meaning":"Trace and say /a/"},{"word":"B","phonetic":"/biː/","meaning":"Trace and say /b/"},{"word":"C","phonetic":"/siː/","meaning":"Trace and say /k/"},{"word":"D","phonetic":"/diː/","meaning":"Trace and say /d/"},{"word":"E","phonetic":"/iː/","meaning":"Trace and say /e/"}]'::jsonb, sentences = '[{"text":"Trace each letter carefully","tip":"Say the sound as you trace"},{"text":"Practice makes perfect","tip":"You are doing great!"}]'::jsonb, read_aloud_text = 'Let us trace some letters! Say each sound as you draw the letter!' WHERE level = 'beginner' AND day_number = 45;

-- Days 46-55: More letter practice and reinforcement
UPDATE lessons SET title = 'Letter Sounds Mix-Up Game', description = 'Match each letter to its correct sound in a fun game', vocabulary = '[{"word":"F","phonetic":"/f/","meaning":"Match to fish"},{"word":"G","phonetic":"/ɡ/","meaning":"Match to goat"},{"word":"H","phonetic":"/h/","meaning":"Match to hat"},{"word":"J","phonetic":"/dʒ/","meaning":"Match to jar"},{"word":"K","phonetic":"/k/","meaning":"Match to kite"}]'::jsonb, sentences = '[{"text":"Which letter makes this sound?","tip":"Listen and match"},{"text":"You are a letter detective","tip":"Great listening skills!"}]'::jsonb, read_aloud_text = 'Can you match each letter to its sound? Let us play the mix-up game!' WHERE level = 'beginner' AND day_number = 46;

UPDATE lessons SET title = 'Capital & Small Letters', description = 'Learn that each letter has a big (capital) and small form', vocabulary = '[{"word":"Aa","phonetic":"/eɪ/","meaning":"Big A, small a"},{"word":"Bb","phonetic":"/biː/","meaning":"Big B, small b"},{"word":"Cc","phonetic":"/siː/","meaning":"Big C, small c"},{"word":"Dd","phonetic":"/diː/","meaning":"Big D, small d"}]'::jsonb, sentences = '[{"text":"Big A and small a","tip":"They make the same sound"},{"text":"Capital letters start sentences","tip":"Small letters come after"}]'::jsonb, read_aloud_text = 'Every letter has two forms — a big capital letter and a small letter! They make the same sound!' WHERE level = 'beginner' AND day_number = 47;

UPDATE lessons SET title = 'Vowel Letters Review', description = 'Review the five vowel letters: A, E, I, O, U', vocabulary = '[{"word":"A","phonetic":"/æ/","meaning":"Vowel letter"},{"word":"E","phonetic":"/ɛ/","meaning":"Vowel letter"},{"word":"I","phonetic":"/ɪ/","meaning":"Vowel letter"},{"word":"O","phonetic":"/ɒ/","meaning":"Vowel letter"},{"word":"U","phonetic":"/ʌ/","meaning":"Vowel letter"}]'::jsonb, sentences = '[{"text":"A E I O U are vowels","tip":"Every word needs a vowel"},{"text":"Vowels are special letters","tip":"They help us make words"}]'::jsonb, read_aloud_text = 'A, E, I, O, U — the five special vowel letters! Every word needs at least one!' WHERE level = 'beginner' AND day_number = 48;

UPDATE lessons SET title = 'Consonant Letters Review', description = 'Review consonant letters B through N', vocabulary = '[{"word":"B","phonetic":"/b/","meaning":"Consonant"},{"word":"C","phonetic":"/k/","meaning":"Consonant"},{"word":"D","phonetic":"/d/","meaning":"Consonant"},{"word":"F","phonetic":"/f/","meaning":"Consonant"},{"word":"G","phonetic":"/ɡ/","meaning":"Consonant"}]'::jsonb, sentences = '[{"text":"Consonants need vowels","tip":"They work together"},{"text":"B C D F G are consonants","tip":"Not vowels!"}]'::jsonb, read_aloud_text = 'Consonants are all the other letters! They team up with vowels to make words!' WHERE level = 'beginner' AND day_number = 49;

UPDATE lessons SET title = 'Letter-Sound Speed Game', description = 'How fast can you say each letter sound?', vocabulary = '[{"word":"L","phonetic":"/l/","meaning":"Quick! Say /l/"},{"word":"M","phonetic":"/m/","meaning":"Quick! Say /m/"},{"word":"N","phonetic":"/n/","meaning":"Quick! Say /n/"},{"word":"P","phonetic":"/p/","meaning":"Quick! Say /p/"},{"word":"R","phonetic":"/r/","meaning":"Quick! Say /r/"}]'::jsonb, sentences = '[{"text":"Say the sound fast","tip":"Speed round!"},{"text":"You are getting faster","tip":"Practice builds speed!"}]'::jsonb, read_aloud_text = 'Speed round! Say each letter sound as fast as you can! Ready, set, go!' WHERE level = 'beginner' AND day_number = 50;

UPDATE lessons SET title = 'Beginning Sounds Detective', description = 'Listen to words and identify the beginning letter', vocabulary = '[{"word":"sun","phonetic":"/s/","meaning":"Starts with S"},{"word":"tree","phonetic":"/t/","meaning":"Starts with T"},{"word":"van","phonetic":"/v/","meaning":"Starts with V"},{"word":"water","phonetic":"/w/","meaning":"Starts with W"},{"word":"zebra","phonetic":"/z/","meaning":"Starts with Z"}]'::jsonb, sentences = '[{"text":"What letter starts this word?","tip":"Listen to the first sound"},{"text":"You are a sound detective","tip":"Great ears!"}]'::jsonb, read_aloud_text = 'Be a detective! Listen to each word and tell me what letter it starts with!' WHERE level = 'beginner' AND day_number = 51;

UPDATE lessons SET title = 'Ending Sounds Discovery', description = 'Learn to hear the last sound in a word', vocabulary = '[{"word":"cat","phonetic":"/t/","meaning":"Ends with /t/"},{"word":"dog","phonetic":"/ɡ/","meaning":"Ends with /g/"},{"word":"bus","phonetic":"/s/","meaning":"Ends with /s/"},{"word":"bed","phonetic":"/d/","meaning":"Ends with /d/"},{"word":"cup","phonetic":"/p/","meaning":"Ends with /p/"}]'::jsonb, sentences = '[{"text":"What sound ends this word?","tip":"Listen to the last sound"},{"text":"Cat ends with /t/","tip":"The last sound matters too!"}]'::jsonb, read_aloud_text = 'Now listen to the END of each word! What is the last sound you hear?' WHERE level = 'beginner' AND day_number = 52;

UPDATE lessons SET title = 'Middle Sounds Discovery', description = 'Learn to hear the middle sound in short words', vocabulary = '[{"word":"cat","phonetic":"/æ/","meaning":"Middle sound is /a/"},{"word":"pen","phonetic":"/ɛ/","meaning":"Middle sound is /e/"},{"word":"sit","phonetic":"/ɪ/","meaning":"Middle sound is /i/"},{"word":"hot","phonetic":"/ɒ/","meaning":"Middle sound is /o/"},{"word":"cup","phonetic":"/ʌ/","meaning":"Middle sound is /u/"}]'::jsonb, sentences = '[{"text":"What is the middle sound?","tip":"The vowel in the middle"},{"text":"Cat has /a/ in the middle","tip":"Stretch the word out"}]'::jsonb, read_aloud_text = 'Listen for the middle sound! Stretch the word out: c-a-t. The middle sound is /a/!' WHERE level = 'beginner' AND day_number = 53;

UPDATE lessons SET title = 'Sound Segmentation', description = 'Break words into individual sounds', vocabulary = '[{"word":"cat","phonetic":"/k/-/æ/-/t/","meaning":"3 sounds: k-a-t"},{"word":"dog","phonetic":"/d/-/ɒ/-/ɡ/","meaning":"3 sounds: d-o-g"},{"word":"sun","phonetic":"/s/-/ʌ/-/n/","meaning":"3 sounds: s-u-n"}]'::jsonb, sentences = '[{"text":"Break the word into sounds","tip":"Say each sound separately"},{"text":"Cat is k-a-t","tip":"Three sounds!"}]'::jsonb, read_aloud_text = 'Let us break words apart! Cat is /k/ /a/ /t/ — three sounds! Can you try?' WHERE level = 'beginner' AND day_number = 54;

UPDATE lessons SET title = 'Sound Blending Introduction', description = 'Put individual sounds together to make words', vocabulary = '[{"word":"/k/-/æ/-/t/","phonetic":"cat","meaning":"Blend to make cat"},{"word":"/d/-/ɒ/-/ɡ/","phonetic":"dog","meaning":"Blend to make dog"},{"word":"/s/-/ʌ/-/n/","phonetic":"sun","meaning":"Blend to make sun"}]'::jsonb, sentences = '[{"text":"Put the sounds together","tip":"Blend them into a word"},{"text":"/k/ /a/ /t/ makes cat","tip":"You are blending!"}]'::jsonb, read_aloud_text = 'Now let us put sounds TOGETHER! /k/ /a/ /t/ — what word is it? Cat! You are blending!' WHERE level = 'beginner' AND day_number = 55;

-- Days 56-60: Phase 2 reinforcement and mastery gate
UPDATE lessons SET title = 'Blending Practice 1', description = 'Blend more three-sound words together', vocabulary = '[{"word":"/p/-/ɪ/-/ɡ/","phonetic":"pig","meaning":"Blend to make pig"},{"word":"/h/-/æ/-/t/","phonetic":"hat","meaning":"Blend to make hat"},{"word":"/b/-/ʌ/-/s/","phonetic":"bus","meaning":"Blend to make bus"}]'::jsonb, sentences = '[{"text":"Blend the sounds","tip":"Say them faster and faster"},{"text":"You made a word","tip":"Blending is your superpower!"}]'::jsonb, read_aloud_text = 'Keep blending! /p/ /i/ /g/ — pig! /h/ /a/ /t/ — hat! You are amazing!' WHERE level = 'beginner' AND day_number = 56;

UPDATE lessons SET title = 'Blending Practice 2', description = 'More blending practice with new words', vocabulary = '[{"word":"/b/-/ɛ/-/d/","phonetic":"bed","meaning":"Blend to make bed"},{"word":"/r/-/ʌ/-/n/","phonetic":"run","meaning":"Blend to make run"},{"word":"/s/-/ɪ/-/t/","phonetic":"sit","meaning":"Blend to make sit"}]'::jsonb, sentences = '[{"text":"Blend faster now","tip":"You are getting better!"},{"text":"Three sounds make a word","tip":"Keep practicing!"}]'::jsonb, read_aloud_text = '/b/ /e/ /d/ — bed! /r/ /u/ /n/ — run! /s/ /i/ /t/ — sit! Fantastic blending!' WHERE level = 'beginner' AND day_number = 57;

UPDATE lessons SET title = 'Letter-Sound Review Game', description = 'Big review of all letters and their sounds', vocabulary = '[{"word":"A-Z","phonetic":"all sounds","meaning":"26 letters, 26 sounds"},{"word":"vowels","phonetic":"a e i o u","meaning":"5 special letters"},{"word":"consonants","phonetic":"the rest","meaning":"21 consonant letters"}]'::jsonb, sentences = '[{"text":"Say every letter sound","tip":"You know them all!"},{"text":"Vowels and consonants","tip":"Letters have two types"}]'::jsonb, read_aloud_text = 'You know all 26 letters and their sounds! Vowels and consonants — you are a letter expert!' WHERE level = 'beginner' AND day_number = 58;

UPDATE lessons SET title = 'Segmenting & Blending Review', description = 'Practice breaking apart and blending words', vocabulary = '[{"word":"map","phonetic":"/m/-/æ/-/p/","meaning":"Segment and blend"},{"word":"net","phonetic":"/n/-/ɛ/-/t/","meaning":"Segment and blend"},{"word":"fox","phonetic":"/f/-/ɒ/-/ks/","meaning":"Segment and blend"}]'::jsonb, sentences = '[{"text":"Break it apart then blend","tip":"Segment first, then blend"},{"text":"You are a word builder","tip":"Keep going!"}]'::jsonb, read_aloud_text = 'Break the word apart: m-a-p. Now blend it back: map! You are a word builder!' WHERE level = 'beginner' AND day_number = 59;

UPDATE lessons SET title = 'Phase 2 Mastery Gate', description = 'Complete the Letter-Sound Connection mastery challenge!', vocabulary = '[{"word":"A","phonetic":"/æ/","meaning":"Say the sound"},{"word":"B","phonetic":"/b/","meaning":"Say the sound"},{"word":"cat","phonetic":"/k/-/æ/-/t/","meaning":"Segment this word"},{"word":"dog","phonetic":"/d/-/ɒ/-/ɡ/","meaning":"Blend this word"}]'::jsonb, sentences = '[{"text":"I know all letter sounds","tip":"Phase 2 champion!"},{"text":"I can blend and segment","tip":"Ready for Phase 3!"}]'::jsonb, read_aloud_text = 'You have completed Phase 2! You know all letters and can blend sounds into words! Phase 3, here we come!' WHERE level = 'beginner' AND day_number = 60;
