
-- Phase 3: CVC Words & Simple Reading (Days 61-90)
UPDATE lessons SET title = 'CVC Words: -at Family', description = 'Read your first word family: cat, bat, hat, mat, sat, rat', vocabulary = '[{"word":"cat","phonetic":"/kæt/","meaning":"A furry pet"},{"word":"bat","phonetic":"/bæt/","meaning":"A flying animal"},{"word":"hat","phonetic":"/hæt/","meaning":"Worn on your head"},{"word":"mat","phonetic":"/mæt/","meaning":"Put on the floor"},{"word":"sat","phonetic":"/sæt/","meaning":"Was sitting"}]'::jsonb, sentences = '[{"text":"The cat sat on the mat","tip":"Three -at words in one sentence!"},{"text":"I see a bat","tip":"Change the first letter to make new words"}]'::jsonb, read_aloud_text = 'Cat, bat, hat, mat, sat! They all end with -at! Change the first letter and make a new word!' WHERE level = 'beginner' AND day_number = 61;

UPDATE lessons SET title = 'CVC Words: -an Family', description = 'Read the -an word family: can, fan, man, pan, ran, van', vocabulary = '[{"word":"can","phonetic":"/kæn/","meaning":"A tin container"},{"word":"fan","phonetic":"/fæn/","meaning":"Keeps you cool"},{"word":"man","phonetic":"/mæn/","meaning":"An adult male"},{"word":"pan","phonetic":"/pæn/","meaning":"Cook with it"},{"word":"van","phonetic":"/væn/","meaning":"A big vehicle"}]'::jsonb, sentences = '[{"text":"The man ran to the van","tip":"Three -an words!"},{"text":"I can fan the pan","tip":"So many -an words!"}]'::jsonb, read_aloud_text = 'Can, fan, man, pan, ran, van! They all end with -an! You are reading!' WHERE level = 'beginner' AND day_number = 62;

UPDATE lessons SET title = 'CVC Words: -ig Family', description = 'Read the -ig word family: big, dig, fig, pig, wig', vocabulary = '[{"word":"big","phonetic":"/bɪɡ/","meaning":"Large in size"},{"word":"dig","phonetic":"/dɪɡ/","meaning":"Make a hole"},{"word":"fig","phonetic":"/fɪɡ/","meaning":"A sweet fruit"},{"word":"pig","phonetic":"/pɪɡ/","meaning":"A farm animal"},{"word":"wig","phonetic":"/wɪɡ/","meaning":"Fake hair"}]'::jsonb, sentences = '[{"text":"The big pig can dig","tip":"Three -ig words!"},{"text":"A pig in a wig","tip":"Funny picture!"}]'::jsonb, read_aloud_text = 'Big, dig, fig, pig, wig! The -ig family! A pig in a wig — how funny!' WHERE level = 'beginner' AND day_number = 63;

UPDATE lessons SET title = 'CVC Words: -ot Family', description = 'Read the -ot word family: hot, pot, dot, got, lot, not', vocabulary = '[{"word":"hot","phonetic":"/hɒt/","meaning":"Very warm"},{"word":"pot","phonetic":"/pɒt/","meaning":"Cook in it"},{"word":"dot","phonetic":"/dɒt/","meaning":"A tiny circle"},{"word":"got","phonetic":"/ɡɒt/","meaning":"Received"},{"word":"not","phonetic":"/nɒt/","meaning":"No, opposite"}]'::jsonb, sentences = '[{"text":"The pot is hot","tip":"Two -ot words!"},{"text":"I got a lot of dots","tip":"Reading sentences!"}]'::jsonb, read_aloud_text = 'Hot, pot, dot, got, lot, not! The -ot family! The pot is hot — be careful!' WHERE level = 'beginner' AND day_number = 64;

UPDATE lessons SET title = 'CVC Words: -ug Family', description = 'Read the -ug word family: bug, hug, mug, rug, tug', vocabulary = '[{"word":"bug","phonetic":"/bʌɡ/","meaning":"A tiny insect"},{"word":"hug","phonetic":"/hʌɡ/","meaning":"Wrap your arms around"},{"word":"mug","phonetic":"/mʌɡ/","meaning":"A big cup"},{"word":"rug","phonetic":"/rʌɡ/","meaning":"A floor mat"},{"word":"tug","phonetic":"/tʌɡ/","meaning":"Pull hard"}]'::jsonb, sentences = '[{"text":"The bug is on the rug","tip":"Two -ug words!"},{"text":"Give me a big hug","tip":"Hug ends with -ug!"}]'::jsonb, read_aloud_text = 'Bug, hug, mug, rug, tug! The -ug family! Give the bug a hug — just kidding!' WHERE level = 'beginner' AND day_number = 65;

UPDATE lessons SET title = 'CVC Words: -en Family', description = 'Read the -en word family: hen, pen, ten, den, men', vocabulary = '[{"word":"hen","phonetic":"/hɛn/","meaning":"A female chicken"},{"word":"pen","phonetic":"/pɛn/","meaning":"You write with it"},{"word":"ten","phonetic":"/tɛn/","meaning":"The number 10"},{"word":"den","phonetic":"/dɛn/","meaning":"An animal home"},{"word":"men","phonetic":"/mɛn/","meaning":"More than one man"}]'::jsonb, sentences = '[{"text":"Ten men have pens","tip":"Three -en words!"},{"text":"The hen is in the den","tip":"Reading is fun!"}]'::jsonb, read_aloud_text = 'Hen, pen, ten, den, men! The -en family! Ten men have pens — can you read that?' WHERE level = 'beginner' AND day_number = 66;

UPDATE lessons SET title = 'CVC Words: -ip Family', description = 'Read the -ip word family: dip, hip, lip, rip, sip, tip, zip', vocabulary = '[{"word":"dip","phonetic":"/dɪp/","meaning":"Put something in"},{"word":"lip","phonetic":"/lɪp/","meaning":"Part of your mouth"},{"word":"sip","phonetic":"/sɪp/","meaning":"Drink a little"},{"word":"tip","phonetic":"/tɪp/","meaning":"The very end"},{"word":"zip","phonetic":"/zɪp/","meaning":"Close your jacket"}]'::jsonb, sentences = '[{"text":"Sip and dip","tip":"Two -ip words!"},{"text":"Zip up your lip","tip":"Funny saying!"}]'::jsonb, read_aloud_text = 'Dip, lip, sip, tip, zip! The -ip family! Sip your drink and zip your jacket!' WHERE level = 'beginner' AND day_number = 67;

UPDATE lessons SET title = 'CVC Words: -op Family', description = 'Read the -op word family: hop, mop, pop, top, stop', vocabulary = '[{"word":"hop","phonetic":"/hɒp/","meaning":"Jump on one foot"},{"word":"mop","phonetic":"/mɒp/","meaning":"Clean the floor"},{"word":"pop","phonetic":"/pɒp/","meaning":"A burst sound"},{"word":"top","phonetic":"/tɒp/","meaning":"The highest point"},{"word":"stop","phonetic":"/stɒp/","meaning":"Do not go"}]'::jsonb, sentences = '[{"text":"Hop to the top","tip":"Two -op words!"},{"text":"Mop and stop","tip":"Rhyming words!"}]'::jsonb, read_aloud_text = 'Hop, mop, pop, top, stop! The -op family! Hop hop hop to the top!' WHERE level = 'beginner' AND day_number = 68;

UPDATE lessons SET title = 'CVC Words: -un Family', description = 'Read the -un word family: bun, fun, gun, run, sun', vocabulary = '[{"word":"bun","phonetic":"/bʌn/","meaning":"A round bread"},{"word":"fun","phonetic":"/fʌn/","meaning":"Enjoyable time"},{"word":"run","phonetic":"/rʌn/","meaning":"Move fast"},{"word":"sun","phonetic":"/sʌn/","meaning":"Bright in the sky"}]'::jsonb, sentences = '[{"text":"Run in the sun","tip":"Two -un words!"},{"text":"It is fun to eat a bun","tip":"Reading is fun!"}]'::jsonb, read_aloud_text = 'Bun, fun, run, sun! The -un family! Run in the sun — it is fun!' WHERE level = 'beginner' AND day_number = 69;

UPDATE lessons SET title = 'CVC Word Family Review', description = 'Review all word families: -at, -an, -ig, -ot, -ug, -en, -ip, -op, -un', vocabulary = '[{"word":"cat","phonetic":"-at","meaning":"Word family"},{"word":"can","phonetic":"-an","meaning":"Word family"},{"word":"big","phonetic":"-ig","meaning":"Word family"},{"word":"hot","phonetic":"-ot","meaning":"Word family"},{"word":"bug","phonetic":"-ug","meaning":"Word family"}]'::jsonb, sentences = '[{"text":"I can read word families","tip":"Nine families learned!"},{"text":"Change the first letter","tip":"Make new words!"}]'::jsonb, read_aloud_text = 'You know nine word families! Change the first letter and make new words! You are a reader!' WHERE level = 'beginner' AND day_number = 70;

-- Days 71-85: Simple Sentences & Sight Words
UPDATE lessons SET title = 'Sight Word: I', description = 'Learn the sight word "I" and use it in sentences', vocabulary = '[{"word":"I","phonetic":"/aɪ/","meaning":"Talking about yourself"},{"word":"am","phonetic":"/æm/","meaning":"A way to say you are"},{"word":"big","phonetic":"/bɪɡ/","meaning":"Large"}]'::jsonb, sentences = '[{"text":"I am big","tip":"I is always a capital letter"},{"text":"I can run","tip":"I is a sight word"},{"text":"I am happy","tip":"Use I to talk about yourself"}]'::jsonb, read_aloud_text = 'I am big! I can run! I am happy! The word I is always a big letter!' WHERE level = 'beginner' AND day_number = 71;

UPDATE lessons SET title = 'Sight Words: the, a', description = 'Learn sight words "the" and "a"', vocabulary = '[{"word":"the","phonetic":"/ðə/","meaning":"Talking about something specific"},{"word":"a","phonetic":"/ə/","meaning":"Talking about one thing"},{"word":"cat","phonetic":"/kæt/","meaning":"A furry pet"}]'::jsonb, sentences = '[{"text":"I see the cat","tip":"The points to a specific cat"},{"text":"I see a dog","tip":"A means any dog"},{"text":"The sun is hot","tip":"The is a sight word"}]'::jsonb, read_aloud_text = 'The cat. A dog. The sun. These small words help us read sentences! The and a are sight words!' WHERE level = 'beginner' AND day_number = 72;

UPDATE lessons SET title = 'Sight Words: is, it', description = 'Learn sight words "is" and "it"', vocabulary = '[{"word":"is","phonetic":"/ɪz/","meaning":"Describes something"},{"word":"it","phonetic":"/ɪt/","meaning":"Points to something"},{"word":"red","phonetic":"/rɛd/","meaning":"A color"}]'::jsonb, sentences = '[{"text":"It is red","tip":"It and is together"},{"text":"The cat is big","tip":"Is describes the cat"},{"text":"It is fun","tip":"Two sight words!"}]'::jsonb, read_aloud_text = 'It is red! It is big! It is fun! Is and it help us make sentences!' WHERE level = 'beginner' AND day_number = 73;

UPDATE lessons SET title = 'Sight Words: in, on', description = 'Learn sight words "in" and "on"', vocabulary = '[{"word":"in","phonetic":"/ɪn/","meaning":"Inside something"},{"word":"on","phonetic":"/ɒn/","meaning":"On top of something"},{"word":"box","phonetic":"/bɒks/","meaning":"A container"}]'::jsonb, sentences = '[{"text":"The cat is in the box","tip":"In means inside"},{"text":"The hat is on the mat","tip":"On means on top"},{"text":"Sit on the rug","tip":"On the rug!"}]'::jsonb, read_aloud_text = 'In the box! On the mat! In and on tell us WHERE things are!' WHERE level = 'beginner' AND day_number = 74;

UPDATE lessons SET title = 'Sight Words: can, see', description = 'Learn sight words "can" and "see"', vocabulary = '[{"word":"can","phonetic":"/kæn/","meaning":"Able to do something"},{"word":"see","phonetic":"/siː/","meaning":"Look with your eyes"},{"word":"run","phonetic":"/rʌn/","meaning":"Move fast"}]'::jsonb, sentences = '[{"text":"I can see the sun","tip":"Two sight words together"},{"text":"Can you see the dog?","tip":"Can asks a question"},{"text":"I can run fast","tip":"Can means you are able to"}]'::jsonb, read_aloud_text = 'I can see! Can you see? I can run! Can is a power word — it means you CAN do it!' WHERE level = 'beginner' AND day_number = 75;

UPDATE lessons SET title = 'Sight Words: he, she, we', description = 'Learn sight words for people: he, she, we', vocabulary = '[{"word":"he","phonetic":"/hiː/","meaning":"A boy or man"},{"word":"she","phonetic":"/ʃiː/","meaning":"A girl or woman"},{"word":"we","phonetic":"/wiː/","meaning":"You and me together"}]'::jsonb, sentences = '[{"text":"He can run","tip":"He is for a boy"},{"text":"She is happy","tip":"She is for a girl"},{"text":"We can play","tip":"We means together"}]'::jsonb, read_aloud_text = 'He can run! She is happy! We can play! He, she, and we talk about people!' WHERE level = 'beginner' AND day_number = 76;

UPDATE lessons SET title = 'Sight Words: my, you', description = 'Learn sight words "my" and "you"', vocabulary = '[{"word":"my","phonetic":"/maɪ/","meaning":"Belongs to me"},{"word":"you","phonetic":"/juː/","meaning":"The person listening"},{"word":"hat","phonetic":"/hæt/","meaning":"Worn on head"}]'::jsonb, sentences = '[{"text":"This is my hat","tip":"My means it belongs to you"},{"text":"Can you see?","tip":"You is the listener"},{"text":"You and I are friends","tip":"You and my together"}]'::jsonb, read_aloud_text = 'My hat! My dog! You can see! My and you are important sight words!' WHERE level = 'beginner' AND day_number = 77;

UPDATE lessons SET title = 'Sight Words: go, no, so', description = 'Learn sight words "go", "no", and "so"', vocabulary = '[{"word":"go","phonetic":"/ɡoʊ/","meaning":"Move to a place"},{"word":"no","phonetic":"/noʊ/","meaning":"The opposite of yes"},{"word":"so","phonetic":"/soʊ/","meaning":"Very much"}]'::jsonb, sentences = '[{"text":"Go to the park","tip":"Go means move"},{"text":"No, I can not","tip":"No means not yes"},{"text":"It is so big","tip":"So means very"}]'::jsonb, read_aloud_text = 'Go! No! So big! These little words are everywhere in reading!' WHERE level = 'beginner' AND day_number = 78;

UPDATE lessons SET title = 'Sight Words: up, and, but', description = 'Learn sight words "up", "and", and "but"', vocabulary = '[{"word":"up","phonetic":"/ʌp/","meaning":"Going higher"},{"word":"and","phonetic":"/ænd/","meaning":"Joins two things"},{"word":"but","phonetic":"/bʌt/","meaning":"However"}]'::jsonb, sentences = '[{"text":"Go up and up","tip":"Up means higher"},{"text":"The cat and the dog","tip":"And joins things"},{"text":"Big but not fat","tip":"But shows a difference"}]'::jsonb, read_aloud_text = 'Up, and, but! The cat AND the dog go UP, but not too high!' WHERE level = 'beginner' AND day_number = 79;

UPDATE lessons SET title = 'Sight Words Review', description = 'Review all sight words learned so far', vocabulary = '[{"word":"I","phonetic":"sight word","meaning":"About yourself"},{"word":"the","phonetic":"sight word","meaning":"Specific thing"},{"word":"is","phonetic":"sight word","meaning":"Describes"},{"word":"can","phonetic":"sight word","meaning":"Able to"},{"word":"see","phonetic":"sight word","meaning":"Look at"}]'::jsonb, sentences = '[{"text":"I can see the cat","tip":"Four sight words!"},{"text":"He is in the van","tip":"Three sight words!"},{"text":"She can go up","tip":"Three sight words!"}]'::jsonb, read_aloud_text = 'You know so many sight words now! I, the, a, is, it, in, on, can, see, he, she, we, my, you, go, no, so, up, and, but!' WHERE level = 'beginner' AND day_number = 80;

-- Days 81-90: Simple reading and Phase 3 mastery
UPDATE lessons SET title = 'Reading Simple Sentences 1', description = 'Read complete sentences using CVC words and sight words', vocabulary = '[{"word":"sat","phonetic":"/sæt/","meaning":"Was sitting"},{"word":"mat","phonetic":"/mæt/","meaning":"A floor cover"},{"word":"big","phonetic":"/bɪɡ/","meaning":"Large"}]'::jsonb, sentences = '[{"text":"The cat sat on the mat","tip":"A famous first sentence!"},{"text":"I can see a big dog","tip":"Read each word carefully"},{"text":"He is in the van","tip":"Use your sight words"}]'::jsonb, read_aloud_text = 'The cat sat on the mat! You just read a real sentence! You are a reader!' WHERE level = 'beginner' AND day_number = 81;

UPDATE lessons SET title = 'Reading Simple Sentences 2', description = 'More sentence reading practice', vocabulary = '[{"word":"run","phonetic":"/rʌn/","meaning":"Move fast"},{"word":"fun","phonetic":"/fʌn/","meaning":"Enjoyable"},{"word":"sun","phonetic":"/sʌn/","meaning":"In the sky"}]'::jsonb, sentences = '[{"text":"We can run in the sun","tip":"Five words!"},{"text":"It is fun to hop","tip":"Use your word families"},{"text":"She is not sad","tip":"Read and understand"}]'::jsonb, read_aloud_text = 'We can run in the sun! It is fun to hop! You are reading sentences!' WHERE level = 'beginner' AND day_number = 82;

UPDATE lessons SET title = 'Reading Simple Sentences 3', description = 'Practice reading longer sentences', vocabulary = '[{"word":"like","phonetic":"/laɪk/","meaning":"Enjoy something"},{"word":"play","phonetic":"/pleɪ/","meaning":"Have fun"},{"word":"with","phonetic":"/wɪð/","meaning":"Together"}]'::jsonb, sentences = '[{"text":"I like to play with my dog","tip":"A longer sentence!"},{"text":"She can see the big red bus","tip":"Reading with colors!"},{"text":"He and I go up the hill","tip":"Two people together"}]'::jsonb, read_aloud_text = 'I like to play with my dog! Longer sentences now! You are getting so good!' WHERE level = 'beginner' AND day_number = 83;

UPDATE lessons SET title = 'Reading Mini Story 1', description = 'Read your first mini story!', vocabulary = '[{"word":"story","phonetic":"/ˈstɔːri/","meaning":"A tale to read"},{"word":"little","phonetic":"/ˈlɪtəl/","meaning":"Small in size"},{"word":"happy","phonetic":"/ˈhæpi/","meaning":"Feeling good"}]'::jsonb, sentences = '[{"text":"The little cat sat on a mat","tip":"Start of the story"},{"text":"A big dog ran to the cat","tip":"What happens next?"},{"text":"The cat and dog are happy","tip":"Happy ending!"}]'::jsonb, read_aloud_text = 'The little cat sat on a mat. A big dog ran to the cat. The cat and dog are happy! Your first story!' WHERE level = 'beginner' AND day_number = 84;

UPDATE lessons SET title = 'Reading Mini Story 2', description = 'Read another fun mini story', vocabulary = '[{"word":"find","phonetic":"/faɪnd/","meaning":"Look for and discover"},{"word":"where","phonetic":"/wɛər/","meaning":"In what place"},{"word":"here","phonetic":"/hɪər/","meaning":"In this place"}]'::jsonb, sentences = '[{"text":"I can not find my hat","tip":"Oh no!"},{"text":"Is it on the bed? No.","tip":"Where could it be?"},{"text":"It is here, on my head!","tip":"Funny ending!"}]'::jsonb, read_aloud_text = 'I can not find my hat! Is it on the bed? No! It is here, on my head! Ha ha!' WHERE level = 'beginner' AND day_number = 85;

UPDATE lessons SET title = 'Reading Comprehension 1', description = 'Read and answer questions about a short text', vocabulary = '[{"word":"name","phonetic":"/neɪm/","meaning":"What you are called"},{"word":"like","phonetic":"/laɪk/","meaning":"Enjoy"},{"word":"best","phonetic":"/bɛst/","meaning":"The most"}]'::jsonb, sentences = '[{"text":"My name is Sam","tip":"Who is talking?"},{"text":"I like to run and play","tip":"What does Sam like?"},{"text":"My best pal is my dog","tip":"Who is Sam''s best pal?"}]'::jsonb, read_aloud_text = 'My name is Sam. I like to run and play. My best pal is my dog. Can you answer: What is his name? What does he like?' WHERE level = 'beginner' AND day_number = 86;

UPDATE lessons SET title = 'Reading Comprehension 2', description = 'Another reading comprehension practice', vocabulary = '[{"word":"park","phonetic":"/pɑːrk/","meaning":"A place to play"},{"word":"swing","phonetic":"/swɪŋ/","meaning":"Goes back and forth"},{"word":"slide","phonetic":"/slaɪd/","meaning":"Go down it"}]'::jsonb, sentences = '[{"text":"We go to the park","tip":"Where are they going?"},{"text":"I sit on the swing","tip":"What does she sit on?"},{"text":"He goes down the slide","tip":"What does he do?"}]'::jsonb, read_aloud_text = 'We go to the park! I sit on the swing. He goes down the slide. Reading and understanding!' WHERE level = 'beginner' AND day_number = 87;

UPDATE lessons SET title = 'CVC & Sight Word Speed Reading', description = 'Read CVC words and sight words as fast as you can', vocabulary = '[{"word":"cat","phonetic":"CVC","meaning":"Read fast!"},{"word":"the","phonetic":"sight","meaning":"Read fast!"},{"word":"big","phonetic":"CVC","meaning":"Read fast!"},{"word":"can","phonetic":"sight","meaning":"Read fast!"},{"word":"run","phonetic":"CVC","meaning":"Read fast!"}]'::jsonb, sentences = '[{"text":"The big cat can run fast","tip":"Speed read!"},{"text":"I see a red bus on the hill","tip":"Faster!"},{"text":"She and he can hop and skip","tip":"You are so fast!"}]'::jsonb, read_aloud_text = 'Speed reading time! Read as fast as you can! The big cat can run! I see a red bus! Go go go!' WHERE level = 'beginner' AND day_number = 88;

UPDATE lessons SET title = 'Phase 3 Review', description = 'Review CVC words, sight words, and sentence reading', vocabulary = '[{"word":"-at family","phonetic":"cat bat hat","meaning":"Word family"},{"word":"-ig family","phonetic":"big pig dig","meaning":"Word family"},{"word":"sight words","phonetic":"I the is can","meaning":"Words to know"}]'::jsonb, sentences = '[{"text":"The big cat sat on my hat","tip":"Word families + sight words"},{"text":"I can see a pig dig in the mud","tip":"Reading champion!"},{"text":"We go up and she can see the sun","tip":"So many words!"}]'::jsonb, read_aloud_text = 'You can read word families, sight words, and sentences! You are amazing! Almost at the halfway mark!' WHERE level = 'beginner' AND day_number = 89;

UPDATE lessons SET title = 'Phase 3 Mastery Gate', description = 'Complete the CVC Words & Reading mastery challenge! You are halfway!', vocabulary = '[{"word":"read","phonetic":"/riːd/","meaning":"You can do this!"},{"word":"words","phonetic":"/wɜːrdz/","meaning":"Building blocks"},{"word":"sentences","phonetic":"/ˈsɛntənsɪz/","meaning":"Words together"}]'::jsonb, sentences = '[{"text":"I can read words and sentences","tip":"Phase 3 champion!"},{"text":"The cat sat on the mat and the dog ran","tip":"A long sentence!"},{"text":"I am a reader now","tip":"Yes you are!"}]'::jsonb, read_aloud_text = 'Phase 3 complete! You are HALFWAY through Level 1! You can read words and sentences! Celebration time!' WHERE level = 'beginner' AND day_number = 90;
