
-- Phase 5: Vocabulary, Grammar & Expression (Days 121-150)
UPDATE lessons SET title = 'Action Words (Verbs) 1', description = 'Learn common action words: run, jump, eat, sleep, play', vocabulary = '[{"word":"run","phonetic":"/rʌn/","meaning":"Move fast on your feet"},{"word":"jump","phonetic":"/dʒʌmp/","meaning":"Leap into the air"},{"word":"eat","phonetic":"/iːt/","meaning":"Put food in your mouth"},{"word":"sleep","phonetic":"/sliːp/","meaning":"Rest with eyes closed"},{"word":"play","phonetic":"/pleɪ/","meaning":"Have fun"}]'::jsonb, sentences = '[{"text":"I run and jump every day","tip":"Action words tell what you DO"},{"text":"We eat, sleep, and play","tip":"Three actions in one sentence!"}]'::jsonb, read_aloud_text = 'Action words tell us what to do! Run! Jump! Eat! Sleep! Play! What action are you doing now?' WHERE level = 'beginner' AND day_number = 121;

UPDATE lessons SET title = 'Action Words (Verbs) 2', description = 'More action words: read, write, draw, sing, dance', vocabulary = '[{"word":"read","phonetic":"/riːd/","meaning":"Look at words"},{"word":"write","phonetic":"/raɪt/","meaning":"Put words on paper"},{"word":"draw","phonetic":"/drɔː/","meaning":"Make pictures"},{"word":"sing","phonetic":"/sɪŋ/","meaning":"Make music with voice"},{"word":"dance","phonetic":"/dæns/","meaning":"Move to music"}]'::jsonb, sentences = '[{"text":"I like to read and write","tip":"School actions"},{"text":"She can sing and dance","tip":"Fun actions!"}]'::jsonb, read_aloud_text = 'More action words! Read, write, draw, sing, dance! Can you act them out?' WHERE level = 'beginner' AND day_number = 122;

UPDATE lessons SET title = 'Describing Words (Adjectives)', description = 'Learn words that describe: big, small, happy, sad, fast, slow', vocabulary = '[{"word":"big","phonetic":"/bɪɡ/","meaning":"Large in size"},{"word":"small","phonetic":"/smɔːl/","meaning":"Tiny in size"},{"word":"happy","phonetic":"/ˈhæpi/","meaning":"Feeling good"},{"word":"fast","phonetic":"/fæst/","meaning":"Moving quickly"},{"word":"slow","phonetic":"/sloʊ/","meaning":"Moving not quickly"}]'::jsonb, sentences = '[{"text":"The big, happy dog is fast","tip":"Describing words add detail"},{"text":"A small, slow turtle","tip":"Two describing words!"}]'::jsonb, read_aloud_text = 'Describing words tell us MORE about things! Big dog! Small cat! Happy bird! They paint pictures with words!' WHERE level = 'beginner' AND day_number = 123;

UPDATE lessons SET title = 'Color Words in Sentences', description = 'Use color words in reading and speaking', vocabulary = '[{"word":"red","phonetic":"/rɛd/","meaning":"Color of apples"},{"word":"blue","phonetic":"/bluː/","meaning":"Color of sky"},{"word":"green","phonetic":"/ɡriːn/","meaning":"Color of grass"},{"word":"yellow","phonetic":"/ˈjɛloʊ/","meaning":"Color of sun"},{"word":"purple","phonetic":"/ˈpɜːrpəl/","meaning":"Mix of red and blue"}]'::jsonb, sentences = '[{"text":"The red apple is on the green grass","tip":"Two color words!"},{"text":"I see a blue sky and yellow sun","tip":"Colors make reading fun!"}]'::jsonb, read_aloud_text = 'Red, blue, green, yellow, purple! Colors make our sentences beautiful and fun to read!' WHERE level = 'beginner' AND day_number = 124;

UPDATE lessons SET title = 'Number Words', description = 'Read number words from one to ten', vocabulary = '[{"word":"one","phonetic":"/wʌn/","meaning":"1"},{"word":"two","phonetic":"/tuː/","meaning":"2"},{"word":"three","phonetic":"/θriː/","meaning":"3"},{"word":"four","phonetic":"/fɔːr/","meaning":"4"},{"word":"five","phonetic":"/faɪv/","meaning":"5"}]'::jsonb, sentences = '[{"text":"I have one dog and two cats","tip":"Number words in sentences"},{"text":"Three birds sit on four branches","tip":"Count and read!"}]'::jsonb, read_aloud_text = 'One, two, three, four, five! Number words help us count in sentences!' WHERE level = 'beginner' AND day_number = 125;

UPDATE lessons SET title = 'Days of the Week', description = 'Learn to read and say all seven days', vocabulary = '[{"word":"Monday","phonetic":"/ˈmʌndeɪ/","meaning":"Day 1"},{"word":"Tuesday","phonetic":"/ˈtjuːzdeɪ/","meaning":"Day 2"},{"word":"Wednesday","phonetic":"/ˈwɛnzdeɪ/","meaning":"Day 3"},{"word":"Thursday","phonetic":"/ˈθɜːrzdeɪ/","meaning":"Day 4"},{"word":"Friday","phonetic":"/ˈfraɪdeɪ/","meaning":"Day 5"}]'::jsonb, sentences = '[{"text":"On Monday I go to school","tip":"Days start with capital letters"},{"text":"Friday is my favorite day","tip":"Which day do you like?"}]'::jsonb, read_aloud_text = 'Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday! Seven days in a week!' WHERE level = 'beginner' AND day_number = 126;

UPDATE lessons SET title = 'My Body Parts', description = 'Read and identify body part words', vocabulary = '[{"word":"head","phonetic":"/hɛd/","meaning":"Top of your body"},{"word":"hand","phonetic":"/hænd/","meaning":"At the end of your arm"},{"word":"foot","phonetic":"/fʊt/","meaning":"You stand on it"},{"word":"eye","phonetic":"/aɪ/","meaning":"You see with it"},{"word":"ear","phonetic":"/ɪər/","meaning":"You hear with it"}]'::jsonb, sentences = '[{"text":"I see with my eyes","tip":"Touch each body part!"},{"text":"I hear with my ears","tip":"Point as you read!"}]'::jsonb, read_aloud_text = 'Head, shoulders, knees and toes! Eyes, ears, mouth and nose! Touch each body part as you say it!' WHERE level = 'beginner' AND day_number = 127;

UPDATE lessons SET title = 'My Family Words', description = 'Learn family member words', vocabulary = '[{"word":"mother","phonetic":"/ˈmʌðər/","meaning":"Your mom"},{"word":"father","phonetic":"/ˈfɑːðər/","meaning":"Your dad"},{"word":"sister","phonetic":"/ˈsɪstər/","meaning":"Girl sibling"},{"word":"brother","phonetic":"/ˈbrʌðər/","meaning":"Boy sibling"},{"word":"family","phonetic":"/ˈfæməli/","meaning":"All together"}]'::jsonb, sentences = '[{"text":"My mother and father love me","tip":"Family words"},{"text":"I play with my sister and brother","tip":"Siblings are fun!"}]'::jsonb, read_aloud_text = 'Mother, father, sister, brother — family! Who is in YOUR family? Tell me!' WHERE level = 'beginner' AND day_number = 128;

UPDATE lessons SET title = 'Food and Drink Words', description = 'Learn common food vocabulary', vocabulary = '[{"word":"water","phonetic":"/ˈwɔːtər/","meaning":"Clear drink"},{"word":"milk","phonetic":"/mɪlk/","meaning":"White drink"},{"word":"rice","phonetic":"/raɪs/","meaning":"Small white grains"},{"word":"bread","phonetic":"/brɛd/","meaning":"Baked from flour"},{"word":"fruit","phonetic":"/fruːt/","meaning":"Sweet natural food"}]'::jsonb, sentences = '[{"text":"I drink water and milk","tip":"Drink words"},{"text":"I eat rice, bread, and fruit","tip":"Food words"}]'::jsonb, read_aloud_text = 'Water, milk, rice, bread, fruit! What food do YOU like to eat? Tell me!' WHERE level = 'beginner' AND day_number = 129;

UPDATE lessons SET title = 'Animal Words', description = 'Read and learn animal names', vocabulary = '[{"word":"lion","phonetic":"/ˈlaɪən/","meaning":"King of the jungle"},{"word":"elephant","phonetic":"/ˈɛlɪfənt/","meaning":"Biggest land animal"},{"word":"butterfly","phonetic":"/ˈbʌtərflaɪ/","meaning":"Beautiful flying insect"},{"word":"dolphin","phonetic":"/ˈdɒlfɪn/","meaning":"Smart sea animal"},{"word":"penguin","phonetic":"/ˈpɛŋɡwɪn/","meaning":"Bird that cannot fly"}]'::jsonb, sentences = '[{"text":"The lion and elephant live in Africa","tip":"Wild animals"},{"text":"A butterfly and dolphin are beautiful","tip":"Nature is wonderful"}]'::jsonb, read_aloud_text = 'Lion, elephant, butterfly, dolphin, penguin! So many amazing animals! Which is your favorite?' WHERE level = 'beginner' AND day_number = 130;

-- Days 131-150: Grammar, expression, and advanced reading
UPDATE lessons SET title = 'Sentences with AM, IS, ARE', description = 'Use am, is, are correctly in sentences', vocabulary = '[{"word":"am","phonetic":"/æm/","meaning":"Used with I"},{"word":"is","phonetic":"/ɪz/","meaning":"Used with he/she/it"},{"word":"are","phonetic":"/ɑːr/","meaning":"Used with we/you/they"}]'::jsonb, sentences = '[{"text":"I am happy","tip":"I + am"},{"text":"She is kind","tip":"She + is"},{"text":"We are friends","tip":"We + are"}]'::jsonb, read_aloud_text = 'I AM happy. She IS kind. We ARE friends. Am, is, and are help us talk about NOW!' WHERE level = 'beginner' AND day_number = 131;

UPDATE lessons SET title = 'Past Tense: -ed Endings', description = 'Learn how -ed makes words about the past', vocabulary = '[{"word":"jumped","phonetic":"/dʒʌmpt/","meaning":"Did jump"},{"word":"played","phonetic":"/pleɪd/","meaning":"Did play"},{"word":"walked","phonetic":"/wɔːkt/","meaning":"Did walk"},{"word":"looked","phonetic":"/lʊkt/","meaning":"Did look"}]'::jsonb, sentences = '[{"text":"I jumped and played yesterday","tip":"-ed means it already happened"},{"text":"She walked and looked around","tip":"Past tense actions"}]'::jsonb, read_aloud_text = 'Add -ed to talk about the past! Jump becomes jumped! Play becomes played! Yesterday I walked!' WHERE level = 'beginner' AND day_number = 132;

UPDATE lessons SET title = 'Plurals: Adding -s', description = 'Learn how -s makes more than one', vocabulary = '[{"word":"cats","phonetic":"/kæts/","meaning":"More than one cat"},{"word":"dogs","phonetic":"/dɒɡz/","meaning":"More than one dog"},{"word":"books","phonetic":"/bʊks/","meaning":"More than one book"},{"word":"trees","phonetic":"/triːz/","meaning":"More than one tree"}]'::jsonb, sentences = '[{"text":"I see two cats and three dogs","tip":"-s means more than one"},{"text":"Many books are under the trees","tip":"Plural words"}]'::jsonb, read_aloud_text = 'One cat, two cats! One dog, three dogs! Add -s to make more than one! Plurals are easy!' WHERE level = 'beginner' AND day_number = 133;

UPDATE lessons SET title = 'Question Words Practice', description = 'Ask and answer questions using who, what, where, when, why, how', vocabulary = '[{"word":"who","phonetic":"/huː/","meaning":"Asking about a person"},{"word":"what","phonetic":"/wɒt/","meaning":"Asking about a thing"},{"word":"where","phonetic":"/wɛər/","meaning":"Asking about a place"},{"word":"when","phonetic":"/wɛn/","meaning":"Asking about time"},{"word":"how","phonetic":"/haʊ/","meaning":"Asking about way"}]'::jsonb, sentences = '[{"text":"Who is your best friend?","tip":"Who asks about people"},{"text":"Where do you live?","tip":"Where asks about places"},{"text":"How are you today?","tip":"How asks about way or feeling"}]'::jsonb, read_aloud_text = 'Who? What? Where? When? Why? How? These words help us ask questions! Ask me a question!' WHERE level = 'beginner' AND day_number = 134;

UPDATE lessons SET title = 'Reading with Expression', description = 'Practice reading with different emotions', vocabulary = '[{"word":"excited","phonetic":"/ɪkˈsaɪtɪd/","meaning":"Very happy and eager"},{"word":"surprised","phonetic":"/sərˈpraɪzd/","meaning":"Did not expect it"},{"word":"worried","phonetic":"/ˈwʌrid/","meaning":"Feeling nervous"}]'::jsonb, sentences = '[{"text":"Wow! That is amazing!","tip":"Read with excitement!"},{"text":"Oh no! Where did it go?","tip":"Read with surprise and worry"},{"text":"I am so happy to see you!","tip":"Read with joy!"}]'::jsonb, read_aloud_text = 'Reading is not just words — it is FEELINGS too! Read with excitement, surprise, and joy!' WHERE level = 'beginner' AND day_number = 135;

UPDATE lessons SET title = 'Punctuation: Period and Question Mark', description = 'Learn how . and ? change how we read', vocabulary = '[{"word":"period","phonetic":"/ˈpɪəriəd/","meaning":"Stop and pause"},{"word":"question mark","phonetic":"/ˈkwɛstʃən/","meaning":"Asking something"},{"word":"sentence","phonetic":"/ˈsɛntəns/","meaning":"A complete thought"}]'::jsonb, sentences = '[{"text":"I like to read.","tip":"Period means stop, voice goes down"},{"text":"Do you like to read?","tip":"Question mark means voice goes up"},{"text":"What is your name?","tip":"Your voice rises at the end"}]'::jsonb, read_aloud_text = 'A period means STOP. Your voice goes down. A question mark means ASK. Your voice goes UP?' WHERE level = 'beginner' AND day_number = 136;

UPDATE lessons SET title = 'Punctuation: Exclamation Mark', description = 'Learn how ! shows strong feelings', vocabulary = '[{"word":"exclamation","phonetic":"/ˌɛkskləˈmeɪʃən/","meaning":"Shows strong feeling"},{"word":"amazing","phonetic":"/əˈmeɪzɪŋ/","meaning":"Wonderful"},{"word":"hooray","phonetic":"/hʊˈreɪ/","meaning":"Celebration word"}]'::jsonb, sentences = '[{"text":"I did it!","tip":"! means say it with feeling!"},{"text":"That is amazing!","tip":"Show excitement!"},{"text":"Hooray! We won!","tip":"Celebrate with your voice!"}]'::jsonb, read_aloud_text = 'The exclamation mark means FEEL IT! I did it! That is AMAZING! Hooray! Read with ENERGY!' WHERE level = 'beginner' AND day_number = 137;

UPDATE lessons SET title = 'Story: The Magic Garden', description = 'Read a longer story with comprehension', vocabulary = '[{"word":"magic","phonetic":"/ˈmædʒɪk/","meaning":"Something wonderful"},{"word":"garden","phonetic":"/ˈɡɑːrdən/","meaning":"Where plants grow"},{"word":"secret","phonetic":"/ˈsiːkrɪt/","meaning":"Hidden from others"}]'::jsonb, sentences = '[{"text":"Sam found a secret garden behind his house","tip":"What did Sam find?"},{"text":"In the magic garden, flowers could talk!","tip":"What was special about it?"},{"text":"The flowers said: Read to us every day!","tip":"What did the flowers want?"},{"text":"Sam read to the flowers and they grew tall and beautiful","tip":"What happened?"}]'::jsonb, read_aloud_text = 'Sam found a secret garden. The flowers could talk! They said: Read to us! And Sam read every day. The end!' WHERE level = 'beginner' AND day_number = 138;

UPDATE lessons SET title = 'Story: The Brave Little Star', description = 'Read a story about courage', vocabulary = '[{"word":"brave","phonetic":"/breɪv/","meaning":"Not afraid"},{"word":"shine","phonetic":"/ʃaɪn/","meaning":"Give off light"},{"word":"bright","phonetic":"/braɪt/","meaning":"Full of light"}]'::jsonb, sentences = '[{"text":"A little star was afraid to shine","tip":"What was the star afraid of?"},{"text":"The moon said: Be brave! The world needs your light!","tip":"Who helped the star?"},{"text":"The little star shone brighter than ever!","tip":"What did the star do?"}]'::jsonb, read_aloud_text = 'A little star was afraid to shine. The moon said: Be brave! And the star shone SO bright! Be brave like the star!' WHERE level = 'beginner' AND day_number = 139;

UPDATE lessons SET title = 'Retelling a Story', description = 'Practice telling a story in your own words', vocabulary = '[{"word":"beginning","phonetic":"/bɪˈɡɪnɪŋ/","meaning":"Start of story"},{"word":"middle","phonetic":"/ˈmɪdəl/","meaning":"What happens"},{"word":"end","phonetic":"/ɛnd/","meaning":"How it finishes"}]'::jsonb, sentences = '[{"text":"First, the cat was lost","tip":"Beginning"},{"text":"Then, she looked everywhere","tip":"Middle"},{"text":"Finally, she found her way home","tip":"End"}]'::jsonb, read_aloud_text = 'Every story has a beginning, middle, and end! First... Then... Finally... Can you retell a story?' WHERE level = 'beginner' AND day_number = 140;

-- Days 141-150: Advanced reading and Phase 5 mastery
UPDATE lessons SET title = 'Reading Dialogue', description = 'Practice reading what characters say', vocabulary = '[{"word":"said","phonetic":"/sɛd/","meaning":"Spoke words"},{"word":"asked","phonetic":"/æskt/","meaning":"Said as a question"},{"word":"replied","phonetic":"/rɪˈplaɪd/","meaning":"Answered back"}]'::jsonb, sentences = '[{"text":"Mom said, Come here please.","tip":"Change voice for what Mom says"},{"text":"Where are we going? asked Tom.","tip":"Voice goes up for the question"},{"text":"To the park! replied Mom.","tip":"Excited voice for Mom"}]'::jsonb, read_aloud_text = 'When you see quotation marks, change your voice! Mom SAID... Tom ASKED... Reading dialogue is like acting!' WHERE level = 'beginner' AND day_number = 141;

UPDATE lessons SET title = 'Prefixes: UN- and RE-', description = 'Learn word beginnings that change meaning', vocabulary = '[{"word":"unhappy","phonetic":"un+happy","meaning":"Not happy"},{"word":"unkind","phonetic":"un+kind","meaning":"Not kind"},{"word":"redo","phonetic":"re+do","meaning":"Do again"},{"word":"reread","phonetic":"re+read","meaning":"Read again"}]'::jsonb, sentences = '[{"text":"I am unhappy, so I will redo it","tip":"UN means not, RE means again"},{"text":"Do not be unkind, reread the rules","tip":"Prefixes change meaning"}]'::jsonb, read_aloud_text = 'UN means NOT! Unhappy means NOT happy! RE means AGAIN! Reread means read AGAIN! Prefixes are word magic!' WHERE level = 'beginner' AND day_number = 142;

UPDATE lessons SET title = 'Suffixes: -ER, -EST', description = 'Learn word endings for comparing: bigger, biggest', vocabulary = '[{"word":"bigger","phonetic":"big+er","meaning":"More big"},{"word":"biggest","phonetic":"big+est","meaning":"Most big"},{"word":"faster","phonetic":"fast+er","meaning":"More fast"},{"word":"fastest","phonetic":"fast+est","meaning":"Most fast"}]'::jsonb, sentences = '[{"text":"The dog is bigger than the cat","tip":"-ER compares two things"},{"text":"The horse is the biggest of all","tip":"-EST is the most of all"}]'::jsonb, read_aloud_text = 'Big, bigger, biggest! Fast, faster, fastest! -ER compares two, -EST is the champion!' WHERE level = 'beginner' AND day_number = 143;

UPDATE lessons SET title = 'Suffixes: -ING, -LY', description = 'Learn -ing for actions happening now and -ly for how', vocabulary = '[{"word":"running","phonetic":"run+ing","meaning":"Doing it now"},{"word":"playing","phonetic":"play+ing","meaning":"Doing it now"},{"word":"quickly","phonetic":"quick+ly","meaning":"In a quick way"},{"word":"slowly","phonetic":"slow+ly","meaning":"In a slow way"}]'::jsonb, sentences = '[{"text":"I am running quickly","tip":"-ING means now, -LY means how"},{"text":"She is playing slowly","tip":"Action + how"}]'::jsonb, read_aloud_text = 'Running! Playing! That is -ING — happening NOW! Quickly! Slowly! That is -LY — tells us HOW!' WHERE level = 'beginner' AND day_number = 144;

UPDATE lessons SET title = 'Synonyms and Antonyms', description = 'Words that mean the same and words that are opposite', vocabulary = '[{"word":"big/large","phonetic":"synonyms","meaning":"Same meaning"},{"word":"happy/glad","phonetic":"synonyms","meaning":"Same meaning"},{"word":"hot/cold","phonetic":"antonyms","meaning":"Opposite meaning"},{"word":"fast/slow","phonetic":"antonyms","meaning":"Opposite meaning"}]'::jsonb, sentences = '[{"text":"Big and large mean the same thing","tip":"Synonyms = same meaning"},{"text":"Hot and cold are opposites","tip":"Antonyms = opposite meaning"}]'::jsonb, read_aloud_text = 'Synonyms are word twins — big and large! Antonyms are word opposites — hot and cold! Words are fun!' WHERE level = 'beginner' AND day_number = 145;

UPDATE lessons SET title = 'Vocabulary Builder: Emotions', description = 'Learn emotion words beyond happy and sad', vocabulary = '[{"word":"excited","phonetic":"/ɪkˈsaɪtɪd/","meaning":"Very happy and eager"},{"word":"nervous","phonetic":"/ˈnɜːrvəs/","meaning":"Worried and uneasy"},{"word":"proud","phonetic":"/praʊd/","meaning":"Feeling good about achievement"},{"word":"curious","phonetic":"/ˈkjʊəriəs/","meaning":"Wanting to know more"},{"word":"grateful","phonetic":"/ˈɡreɪtfəl/","meaning":"Thankful"}]'::jsonb, sentences = '[{"text":"I am excited and curious","tip":"Two emotion words!"},{"text":"She feels proud and grateful","tip":"Positive emotions!"}]'::jsonb, read_aloud_text = 'Happy, sad, excited, nervous, proud, curious, grateful! So many ways to describe how you feel!' WHERE level = 'beginner' AND day_number = 146;

UPDATE lessons SET title = 'Fluent Paragraph Reading 1', description = 'Read a paragraph about school life fluently', vocabulary = '[{"word":"classroom","phonetic":"/ˈklæsruːm/","meaning":"Where lessons happen"},{"word":"teacher","phonetic":"/ˈtiːtʃər/","meaning":"Person who teaches"},{"word":"favorite","phonetic":"/ˈfeɪvərɪt/","meaning":"The one you like most"}]'::jsonb, sentences = '[{"text":"I love going to school every day","tip":"Read smoothly"},{"text":"My classroom is bright and colorful","tip":"Keep flowing"},{"text":"My teacher reads us stories, which is my favorite part","tip":"Long sentence! You can do it!"}]'::jsonb, read_aloud_text = 'I love going to school. My classroom is bright and colorful. My teacher reads us stories, which is my favorite part!' WHERE level = 'beginner' AND day_number = 147;

UPDATE lessons SET title = 'Fluent Paragraph Reading 2', description = 'Read a paragraph about nature fluently', vocabulary = '[{"word":"nature","phonetic":"/ˈneɪtʃər/","meaning":"The natural world"},{"word":"forest","phonetic":"/ˈfɒrɪst/","meaning":"Many trees together"},{"word":"wonderful","phonetic":"/ˈwʌndərfəl/","meaning":"Amazing"}]'::jsonb, sentences = '[{"text":"Nature is wonderful and beautiful","tip":"Read with feeling"},{"text":"In the forest, birds sing and rivers flow","tip":"Paint a picture with words"},{"text":"I love to explore the wonderful world around me","tip":"Express the wonder!"}]'::jsonb, read_aloud_text = 'Nature is wonderful! In the forest, birds sing and rivers flow. I love to explore! Read like you mean it!' WHERE level = 'beginner' AND day_number = 148;

UPDATE lessons SET title = 'Phase 5 Review', description = 'Review vocabulary, grammar, expression, and fluency', vocabulary = '[{"word":"verbs","phonetic":"action words","meaning":"What you do"},{"word":"adjectives","phonetic":"describing words","meaning":"What things are like"},{"word":"expression","phonetic":"feelings in voice","meaning":"How you read"}]'::jsonb, sentences = '[{"text":"I can read with expression and fluency","tip":"Phase 5 skills!"},{"text":"I know verbs, adjectives, and question words","tip":"Grammar champion!"}]'::jsonb, read_aloud_text = 'You know action words, describing words, question words, grammar, and fluent reading! One more phase to go!' WHERE level = 'beginner' AND day_number = 149;

UPDATE lessons SET title = 'Phase 5 Mastery Gate', description = 'Complete the Vocabulary & Grammar mastery challenge!', vocabulary = '[{"word":"vocabulary","phonetic":"words you know","meaning":"Your word bank"},{"word":"grammar","phonetic":"language rules","meaning":"How words work together"},{"word":"mastery","phonetic":"being really good","meaning":"Expert level"}]'::jsonb, sentences = '[{"text":"I have a rich vocabulary","tip":"Phase 5 champion!"},{"text":"I understand grammar and expression","tip":"Almost done with Level 1!"}]'::jsonb, read_aloud_text = 'Phase 5 complete! Your vocabulary is rich, your grammar is strong, and you read with beautiful expression!' WHERE level = 'beginner' AND day_number = 150;
