
-- Phase 4: Digraphs, Blends & Fluency Building (Days 91-120)
UPDATE lessons SET title = 'Digraph: SH', description = 'Learn the SH sound in ship, shell, and shoe', vocabulary = '[{"word":"ship","phonetic":"/ʃɪp/","meaning":"Sails on water"},{"word":"shell","phonetic":"/ʃɛl/","meaning":"Found at the beach"},{"word":"shoe","phonetic":"/ʃuː/","meaning":"Worn on feet"},{"word":"fish","phonetic":"/fɪʃ/","meaning":"SH at the end"}]'::jsonb, sentences = '[{"text":"The ship has a shell","tip":"SH makes one sound from two letters"},{"text":"Put on your shoe","tip":"SH is in shoe"}]'::jsonb, read_aloud_text = 'S and H together make the SH sound! Ship, shell, shoe, fish — can you hear SH?' WHERE level = 'beginner' AND day_number = 91;

UPDATE lessons SET title = 'Digraph: CH', description = 'Learn the CH sound in chair, cheese, and chin', vocabulary = '[{"word":"chair","phonetic":"/tʃɛər/","meaning":"You sit on it"},{"word":"cheese","phonetic":"/tʃiːz/","meaning":"Made from milk"},{"word":"chin","phonetic":"/tʃɪn/","meaning":"Below your mouth"},{"word":"much","phonetic":"/mʌtʃ/","meaning":"A lot"}]'::jsonb, sentences = '[{"text":"Sit on the chair","tip":"CH makes one sound"},{"text":"I like cheese so much","tip":"CH at start and end!"}]'::jsonb, read_aloud_text = 'C and H together make the CH sound! Chair, cheese, chin — say CH!' WHERE level = 'beginner' AND day_number = 92;

UPDATE lessons SET title = 'Digraph: TH', description = 'Learn the TH sound in this, that, and three', vocabulary = '[{"word":"this","phonetic":"/ðɪs/","meaning":"Points to something near"},{"word":"that","phonetic":"/ðæt/","meaning":"Points to something far"},{"word":"three","phonetic":"/θriː/","meaning":"The number 3"},{"word":"math","phonetic":"/mæθ/","meaning":"Numbers subject"}]'::jsonb, sentences = '[{"text":"This is my hat","tip":"TH at the start"},{"text":"I can count to three","tip":"TH can sound soft or hard"}]'::jsonb, read_aloud_text = 'T and H make the TH sound! This, that, three — TH has two ways to say it!' WHERE level = 'beginner' AND day_number = 93;

UPDATE lessons SET title = 'Digraph: WH', description = 'Learn the WH sound in what, when, where, why', vocabulary = '[{"word":"what","phonetic":"/wɒt/","meaning":"Asking about something"},{"word":"when","phonetic":"/wɛn/","meaning":"Asking about time"},{"word":"where","phonetic":"/wɛər/","meaning":"Asking about place"},{"word":"why","phonetic":"/waɪ/","meaning":"Asking for reason"}]'::jsonb, sentences = '[{"text":"What is this?","tip":"WH asks questions"},{"text":"Where is the cat?","tip":"WH question words"}]'::jsonb, read_aloud_text = 'W and H make question words! What? When? Where? Why? WH words help us ask!' WHERE level = 'beginner' AND day_number = 94;

UPDATE lessons SET title = 'Digraph Review & Practice', description = 'Review all digraphs: SH, CH, TH, WH', vocabulary = '[{"word":"ship","phonetic":"SH","meaning":"SH digraph"},{"word":"chair","phonetic":"CH","meaning":"CH digraph"},{"word":"this","phonetic":"TH","meaning":"TH digraph"},{"word":"what","phonetic":"WH","meaning":"WH digraph"}]'::jsonb, sentences = '[{"text":"What is on the ship?","tip":"WH and SH in one sentence!"},{"text":"The cheese is on the chair","tip":"Two CH words!"}]'::jsonb, read_aloud_text = 'SH, CH, TH, WH — four digraphs mastered! Two letters making one sound!' WHERE level = 'beginner' AND day_number = 95;

-- Blends
UPDATE lessons SET title = 'Blend: BL, CL, FL', description = 'Learn consonant blends at the start of words', vocabulary = '[{"word":"blue","phonetic":"/bluː/","meaning":"A color"},{"word":"clock","phonetic":"/klɒk/","meaning":"Tells time"},{"word":"flag","phonetic":"/flæɡ/","meaning":"Waves in the wind"}]'::jsonb, sentences = '[{"text":"The blue flag is big","tip":"BL and FL blends"},{"text":"Look at the clock","tip":"CL blend"}]'::jsonb, read_aloud_text = 'Blends are two consonants together! BL in blue, CL in clock, FL in flag!' WHERE level = 'beginner' AND day_number = 96;

UPDATE lessons SET title = 'Blend: BR, CR, DR', description = 'Learn BR, CR, DR blends', vocabulary = '[{"word":"bread","phonetic":"/brɛd/","meaning":"Made from flour"},{"word":"crab","phonetic":"/kræb/","meaning":"Lives in the sea"},{"word":"drum","phonetic":"/drʌm/","meaning":"A musical instrument"}]'::jsonb, sentences = '[{"text":"Eat the bread","tip":"BR blend"},{"text":"The crab and the drum","tip":"CR and DR blends"}]'::jsonb, read_aloud_text = 'BR in bread, CR in crab, DR in drum! Two consonants blended together!' WHERE level = 'beginner' AND day_number = 97;

UPDATE lessons SET title = 'Blend: GR, PR, TR', description = 'Learn GR, PR, TR blends', vocabulary = '[{"word":"green","phonetic":"/ɡriːn/","meaning":"A nature color"},{"word":"prince","phonetic":"/prɪns/","meaning":"A royal boy"},{"word":"tree","phonetic":"/triː/","meaning":"Grows tall"}]'::jsonb, sentences = '[{"text":"The green tree is tall","tip":"GR and TR blends"},{"text":"The prince plays","tip":"PR blend"}]'::jsonb, read_aloud_text = 'GR in green, PR in prince, TR in tree! Blends are everywhere!' WHERE level = 'beginner' AND day_number = 98;

UPDATE lessons SET title = 'Blend: SN, SP, ST, SW', description = 'Learn S-blends', vocabulary = '[{"word":"snake","phonetic":"/sneɪk/","meaning":"Slithers"},{"word":"spoon","phonetic":"/spuːn/","meaning":"Eat with it"},{"word":"star","phonetic":"/stɑːr/","meaning":"Twinkles"},{"word":"swim","phonetic":"/swɪm/","meaning":"Move in water"}]'::jsonb, sentences = '[{"text":"A snake by the star","tip":"SN and ST blends"},{"text":"Swim with a spoon","tip":"SW and SP blends — silly!"}]'::jsonb, read_aloud_text = 'SN, SP, ST, SW — so many S-blends! Snake, spoon, star, swim!' WHERE level = 'beginner' AND day_number = 99;

UPDATE lessons SET title = 'Blend Review Game', description = 'Mix and match all consonant blends', vocabulary = '[{"word":"blue","phonetic":"BL","meaning":"BL blend"},{"word":"crab","phonetic":"CR","meaning":"CR blend"},{"word":"tree","phonetic":"TR","meaning":"TR blend"},{"word":"swim","phonetic":"SW","meaning":"SW blend"}]'::jsonb, sentences = '[{"text":"Match the blend to the word","tip":"Listen for two consonants"},{"text":"Blends make reading fun","tip":"You know so many!"}]'::jsonb, read_aloud_text = 'You know all the blends! BL, CL, FL, BR, CR, DR, GR, PR, TR, SN, SP, ST, SW!' WHERE level = 'beginner' AND day_number = 100;

-- Days 101-110: Long vowels and magic E
UPDATE lessons SET title = 'Magic E: Long A', description = 'Learn how silent E makes A say its name: cake, lake, name', vocabulary = '[{"word":"cake","phonetic":"/keɪk/","meaning":"Sweet dessert"},{"word":"lake","phonetic":"/leɪk/","meaning":"A body of water"},{"word":"name","phonetic":"/neɪm/","meaning":"What you are called"},{"word":"game","phonetic":"/ɡeɪm/","meaning":"Something you play"}]'::jsonb, sentences = '[{"text":"I ate cake by the lake","tip":"Magic E makes A say its name"},{"text":"My name is in the game","tip":"A says /eɪ/ with magic E"}]'::jsonb, read_aloud_text = 'Magic E is here! When E sits at the end, A says its name! Cake, lake, name, game!' WHERE level = 'beginner' AND day_number = 101;

UPDATE lessons SET title = 'Magic E: Long I', description = 'Silent E makes I say its name: bike, kite, time, nine', vocabulary = '[{"word":"bike","phonetic":"/baɪk/","meaning":"You ride it"},{"word":"kite","phonetic":"/kaɪt/","meaning":"Flies in the sky"},{"word":"time","phonetic":"/taɪm/","meaning":"Hours and minutes"},{"word":"nine","phonetic":"/naɪn/","meaning":"The number 9"}]'::jsonb, sentences = '[{"text":"Ride my bike and fly a kite","tip":"Magic E makes I long"},{"text":"It is time, it is nine","tip":"I says its name!"}]'::jsonb, read_aloud_text = 'Magic E makes I say its name too! Bike, kite, time, nine! I says /aɪ/!' WHERE level = 'beginner' AND day_number = 102;

UPDATE lessons SET title = 'Magic E: Long O', description = 'Silent E makes O say its name: home, bone, nose, rope', vocabulary = '[{"word":"home","phonetic":"/hoʊm/","meaning":"Where you live"},{"word":"bone","phonetic":"/boʊn/","meaning":"Inside your body"},{"word":"nose","phonetic":"/noʊz/","meaning":"On your face"},{"word":"rope","phonetic":"/roʊp/","meaning":"Long and strong"}]'::jsonb, sentences = '[{"text":"Go home and touch your nose","tip":"Magic E makes O long"},{"text":"The dog has a bone","tip":"O says /oʊ/!"}]'::jsonb, read_aloud_text = 'O says its name with magic E! Home, bone, nose, rope! The magic E is powerful!' WHERE level = 'beginner' AND day_number = 103;

UPDATE lessons SET title = 'Magic E: Long U', description = 'Silent E makes U say its name: cute, tube, huge, mule', vocabulary = '[{"word":"cute","phonetic":"/kjuːt/","meaning":"Very pretty"},{"word":"tube","phonetic":"/tjuːb/","meaning":"A hollow cylinder"},{"word":"huge","phonetic":"/hjuːdʒ/","meaning":"Very very big"},{"word":"mule","phonetic":"/mjuːl/","meaning":"Half horse, half donkey"}]'::jsonb, sentences = '[{"text":"The cute mule is huge","tip":"Magic E makes U long"},{"text":"Look in the tube","tip":"U says /juː/!"}]'::jsonb, read_aloud_text = 'U says its name with magic E! Cute, tube, huge, mule! Magic E is the best!' WHERE level = 'beginner' AND day_number = 104;

UPDATE lessons SET title = 'Magic E Review', description = 'Review all magic E patterns: a_e, i_e, o_e, u_e', vocabulary = '[{"word":"cake","phonetic":"a_e","meaning":"Long A"},{"word":"bike","phonetic":"i_e","meaning":"Long I"},{"word":"home","phonetic":"o_e","meaning":"Long O"},{"word":"cute","phonetic":"u_e","meaning":"Long U"}]'::jsonb, sentences = '[{"text":"Bake a cake at home","tip":"Two magic E words!"},{"text":"The cute kite is mine","tip":"Magic E everywhere!"}]'::jsonb, read_aloud_text = 'Magic E review! A says /eɪ/, I says /aɪ/, O says /oʊ/, U says /juː/! You are a magic E master!' WHERE level = 'beginner' AND day_number = 105;

-- Days 106-120: Fluency building, sentences, comprehension
UPDATE lessons SET title = 'Vowel Teams: AI, AY', description = 'Two letters that make the long A sound: rain, play', vocabulary = '[{"word":"rain","phonetic":"/reɪn/","meaning":"Water from clouds"},{"word":"train","phonetic":"/treɪn/","meaning":"Rides on tracks"},{"word":"play","phonetic":"/pleɪ/","meaning":"Have fun"},{"word":"day","phonetic":"/deɪ/","meaning":"24 hours"}]'::jsonb, sentences = '[{"text":"We play in the rain","tip":"AI and AY both say long A"},{"text":"The train comes today","tip":"AI in train, AY in today"}]'::jsonb, read_aloud_text = 'AI and AY both make the long A sound! Rain, train, play, day!' WHERE level = 'beginner' AND day_number = 106;

UPDATE lessons SET title = 'Vowel Teams: EE, EA', description = 'Two letters that make the long E sound: tree, beach', vocabulary = '[{"word":"tree","phonetic":"/triː/","meaning":"Grows tall"},{"word":"see","phonetic":"/siː/","meaning":"Look at"},{"word":"beach","phonetic":"/biːtʃ/","meaning":"Sandy shore"},{"word":"read","phonetic":"/riːd/","meaning":"Look at words"}]'::jsonb, sentences = '[{"text":"I see a tree at the beach","tip":"EE and EA both say long E"},{"text":"Read under the tree","tip":"EA in read, EE in tree"}]'::jsonb, read_aloud_text = 'EE and EA both make the long E sound! Tree, see, beach, read!' WHERE level = 'beginner' AND day_number = 107;

UPDATE lessons SET title = 'Vowel Teams: OA, OW', description = 'Two letters that make the long O sound: boat, snow', vocabulary = '[{"word":"boat","phonetic":"/boʊt/","meaning":"Floats on water"},{"word":"coat","phonetic":"/koʊt/","meaning":"Keeps you warm"},{"word":"snow","phonetic":"/snoʊ/","meaning":"White and cold"},{"word":"grow","phonetic":"/ɡroʊ/","meaning":"Get bigger"}]'::jsonb, sentences = '[{"text":"The boat is in the snow","tip":"OA and OW say long O"},{"text":"I grow in my coat","tip":"OW in grow, OA in coat"}]'::jsonb, read_aloud_text = 'OA and OW both make the long O sound! Boat, coat, snow, grow!' WHERE level = 'beginner' AND day_number = 108;

UPDATE lessons SET title = 'Vowel Teams Review', description = 'Practice all vowel teams: AI/AY, EE/EA, OA/OW', vocabulary = '[{"word":"rain","phonetic":"AI","meaning":"Long A team"},{"word":"tree","phonetic":"EE","meaning":"Long E team"},{"word":"boat","phonetic":"OA","meaning":"Long O team"}]'::jsonb, sentences = '[{"text":"I see rain on the boat","tip":"Multiple vowel teams"},{"text":"Play by the tree in the snow","tip":"AY, EE, OW all together!"}]'::jsonb, read_aloud_text = 'Vowel teams work together! AI/AY for A, EE/EA for E, OA/OW for O!' WHERE level = 'beginner' AND day_number = 109;

UPDATE lessons SET title = 'R-Controlled Vowels: AR', description = 'Learn how R changes vowels: car, star, park, farm', vocabulary = '[{"word":"car","phonetic":"/kɑːr/","meaning":"Drives on roads"},{"word":"star","phonetic":"/stɑːr/","meaning":"Twinkles at night"},{"word":"park","phonetic":"/pɑːrk/","meaning":"Play outside"},{"word":"farm","phonetic":"/fɑːrm/","meaning":"Animals and crops"}]'::jsonb, sentences = '[{"text":"Drive the car to the park","tip":"AR changes the A sound"},{"text":"I see a star on the farm","tip":"AR is a bossy R!"}]'::jsonb, read_aloud_text = 'When R comes after A, it makes a new sound! Car, star, park, farm — AR!' WHERE level = 'beginner' AND day_number = 110;

UPDATE lessons SET title = 'R-Controlled Vowels: OR, IR, UR, ER', description = 'More R-controlled vowels in words', vocabulary = '[{"word":"fork","phonetic":"/fɔːrk/","meaning":"Eat with it"},{"word":"bird","phonetic":"/bɜːrd/","meaning":"Flies in sky"},{"word":"turn","phonetic":"/tɜːrn/","meaning":"Go around"},{"word":"her","phonetic":"/hɜːr/","meaning":"Belongs to she"}]'::jsonb, sentences = '[{"text":"The bird can turn","tip":"IR and UR sound the same!"},{"text":"Give her the fork","tip":"ER and OR sounds"}]'::jsonb, read_aloud_text = 'R is bossy! OR in fork, IR in bird, UR in turn, ER in her! R changes every vowel!' WHERE level = 'beginner' AND day_number = 111;

UPDATE lessons SET title = 'Fluency: Reading Paragraphs 1', description = 'Read a short paragraph smoothly', vocabulary = '[{"word":"morning","phonetic":"/ˈmɔːrnɪŋ/","meaning":"Start of the day"},{"word":"breakfast","phonetic":"/ˈbrɛkfəst/","meaning":"First meal"},{"word":"school","phonetic":"/skuːl/","meaning":"Where you learn"}]'::jsonb, sentences = '[{"text":"In the morning, I eat breakfast","tip":"Read smoothly, not word by word"},{"text":"Then I go to school","tip":"Keep your voice flowing"},{"text":"I like school a lot","tip":"Read like you are talking"}]'::jsonb, read_aloud_text = 'In the morning, I eat breakfast. Then I go to school. I like school a lot. Read it smoothly!' WHERE level = 'beginner' AND day_number = 112;

UPDATE lessons SET title = 'Fluency: Reading Paragraphs 2', description = 'Read another paragraph with expression', vocabulary = '[{"word":"garden","phonetic":"/ˈɡɑːrdən/","meaning":"Where plants grow"},{"word":"flowers","phonetic":"/ˈflaʊərz/","meaning":"Pretty plants"},{"word":"beautiful","phonetic":"/ˈbjuːtɪfəl/","meaning":"Very pretty"}]'::jsonb, sentences = '[{"text":"I have a garden at home","tip":"Read with feeling"},{"text":"The flowers are beautiful","tip":"Show excitement!"},{"text":"I water them every day","tip":"Smooth reading"}]'::jsonb, read_aloud_text = 'I have a garden at home. The flowers are beautiful! I water them every day. Read with feeling!' WHERE level = 'beginner' AND day_number = 113;

UPDATE lessons SET title = 'Story Time: The Lost Kitten', description = 'Read a complete short story', vocabulary = '[{"word":"kitten","phonetic":"/ˈkɪtən/","meaning":"A baby cat"},{"word":"lost","phonetic":"/lɒst/","meaning":"Cannot find the way"},{"word":"found","phonetic":"/faʊnd/","meaning":"Discovered"}]'::jsonb, sentences = '[{"text":"A little kitten was lost","tip":"Beginning of story"},{"text":"She looked under the bed and in the box","tip":"Middle of story"},{"text":"She found her way home at last!","tip":"Happy ending!"}]'::jsonb, read_aloud_text = 'A little kitten was lost. She looked under the bed and in the box. She found her way home at last! The end!' WHERE level = 'beginner' AND day_number = 114;

UPDATE lessons SET title = 'Story Time: The Brave Puppy', description = 'Read another complete story with questions', vocabulary = '[{"word":"brave","phonetic":"/breɪv/","meaning":"Not afraid"},{"word":"puppy","phonetic":"/ˈpʌpi/","meaning":"A baby dog"},{"word":"rescued","phonetic":"/ˈrɛskjuːd/","meaning":"Saved from danger"}]'::jsonb, sentences = '[{"text":"A brave puppy lived on a farm","tip":"Who is the story about?"},{"text":"One day, the puppy heard a cry for help","tip":"What happened?"},{"text":"The puppy rescued the little bird!","tip":"How did it end?"}]'::jsonb, read_aloud_text = 'A brave puppy lived on a farm. One day, the puppy heard a cry for help. The puppy rescued a little bird!' WHERE level = 'beginner' AND day_number = 115;

-- Days 116-120
UPDATE lessons SET title = 'Compound Words', description = 'Two small words make one big word: sunshine, rainbow, football', vocabulary = '[{"word":"sunshine","phonetic":"sun+shine","meaning":"Sun light"},{"word":"rainbow","phonetic":"rain+bow","meaning":"Colors in the sky"},{"word":"football","phonetic":"foot+ball","meaning":"A sport"},{"word":"bedroom","phonetic":"bed+room","meaning":"Where you sleep"}]'::jsonb, sentences = '[{"text":"I see sunshine and a rainbow","tip":"Two words in one!"},{"text":"Play football in the bedroom?","tip":"That would be silly!"}]'::jsonb, read_aloud_text = 'Compound words are two words joined together! Sun + shine = sunshine! Rain + bow = rainbow!' WHERE level = 'beginner' AND day_number = 116;

UPDATE lessons SET title = 'Contractions Introduction', description = 'Learn short forms: I am = I''m, cannot = can''t', vocabulary = '[{"word":"I''m","phonetic":"I am","meaning":"Short for I am"},{"word":"can''t","phonetic":"cannot","meaning":"Short for cannot"},{"word":"it''s","phonetic":"it is","meaning":"Short for it is"},{"word":"don''t","phonetic":"do not","meaning":"Short for do not"}]'::jsonb, sentences = '[{"text":"I''m happy and I can''t wait","tip":"Apostrophe replaces letters"},{"text":"It''s fun and I don''t want to stop","tip":"Short forms in action"}]'::jsonb, read_aloud_text = 'Contractions make words shorter! I am becomes I''m! Cannot becomes can''t! The apostrophe is the magic mark!' WHERE level = 'beginner' AND day_number = 117;

UPDATE lessons SET title = 'Fluency Speed Reading', description = 'Read sentences as quickly and smoothly as you can', vocabulary = '[{"word":"quickly","phonetic":"/ˈkwɪkli/","meaning":"Fast"},{"word":"smoothly","phonetic":"/ˈsmuːðli/","meaning":"Without stopping"},{"word":"fluent","phonetic":"/ˈfluːənt/","meaning":"Reading well"}]'::jsonb, sentences = '[{"text":"The cat sat on the mat and looked at the hat","tip":"Read without stopping"},{"text":"I can see a big red bus going up the hill","tip":"Smooth and steady"},{"text":"She ran to the park and played with her dog","tip":"You are so fluent!"}]'::jsonb, read_aloud_text = 'Speed reading! Read quickly and smoothly! Do not stop between words! You are becoming fluent!' WHERE level = 'beginner' AND day_number = 118;

UPDATE lessons SET title = 'Phase 4 Review', description = 'Review digraphs, blends, magic E, vowel teams, and fluency', vocabulary = '[{"word":"SH CH TH","phonetic":"digraphs","meaning":"Two letters, one sound"},{"word":"BL CR TR","phonetic":"blends","meaning":"Two consonants blended"},{"word":"magic E","phonetic":"a_e i_e o_e","meaning":"Silent E makes vowels long"}]'::jsonb, sentences = '[{"text":"The ship sailed on the blue lake","tip":"Digraph and blend together"},{"text":"I can ride my bike home in the rain","tip":"Magic E and vowel team"}]'::jsonb, read_aloud_text = 'You know digraphs, blends, magic E, vowel teams, and R-controlled vowels! What a reader you are!' WHERE level = 'beginner' AND day_number = 119;

UPDATE lessons SET title = 'Phase 4 Mastery Gate', description = 'Complete the Fluency Building mastery challenge!', vocabulary = '[{"word":"fluent","phonetic":"reading skill","meaning":"Reading smoothly"},{"word":"confident","phonetic":"reading skill","meaning":"Reading with confidence"},{"word":"reader","phonetic":"that is you!","meaning":"Someone who reads"}]'::jsonb, sentences = '[{"text":"I am a fluent reader","tip":"Phase 4 champion!"},{"text":"I can read stories and sentences","tip":"You are amazing!"},{"text":"Phase 5 awaits my adventure","tip":"Almost there!"}]'::jsonb, read_aloud_text = 'Phase 4 complete! You read fluently, confidently, and smoothly! Phase 5 is next — the final stretch!' WHERE level = 'beginner' AND day_number = 120;
